package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.time.Duration
import kotlin.Boolean

public abstract class ActivityLogging(
  retentionPeriod: Duration,
  enabled: Boolean,
  monitoringEnabled: Boolean,
  securityAlertsEnabled: Boolean,
  loggingService: LoggingService,
) : Logging(retentionPeriod, enabled, monitoringEnabled, securityAlertsEnabled, loggingService)
