package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Agnostic(
  codeModules: CodeModule,
  codeRepository: CodeRepository,
  functionalities: Functionality,
  creation_time: ZonedDateTime,
  description: String,
  id: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : OperatingSystemArchitecture(codeModules, codeRepository, functionalities, creation_time,
    description, id, labels, name, raw, parent, underlyingNode)
