package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.MutableMap

/**
 * Represents a rule that combines two other rules using a logical AND operation. This means that
 * both rules must be satisfied for the combined rule to be satisfied.
 */
public abstract class AndRule(
  dataLocation: DataLocation,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : PolicyRule(dataLocation, creation_time, description, labels, name, raw, parent, underlyingNode)
    {
  init {
    this.name = Name(localName = name)
  }

  override fun equals(other: Any?): Boolean = other is AndRule &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
