package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Scope contains the resource ID of the protected resource.
 */
public abstract class AnomalyDetection(
  public val enabled: Boolean?,
  public val applicationLogging: ApplicationLogging?,
  underlyingNode: Node?,
) : Auditing(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is AnomalyDetection &&
              super.equals(other) &&
              other.enabled == this.enabled &&
              other.applicationLogging == this.applicationLogging

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              enabled,
              applicationLogging,
          )
}
