package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class AnomalyDetection(
  enabled: Boolean,
  applicationLogging: ApplicationLogging,
  underlyingNode: Node,
) : Auditing(underlyingNode)
