package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class AnomalyDetection(
  public val enabled: Boolean,
  public val applicationLogging: ApplicationLogging,
  underlyingNode: Node,
) : Auditing(underlyingNode)
