package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import java.util.List
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Application(
  programmingVersion: String,
  programmingLanguage: String,
  translationUnits: List<String>,
  automaticUpdates: AutomaticUpdates,
  compute: Compute,
  libraries: Library,
  codeRepository: CodeRepository,
  functionalities: Functionality,
  codeModules: CodeModule,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
  underlyingNode: Node,
) : Component(libraries, codeRepository, functionalities, codeModules, raw, creation_time, labels,
    name, description, id, parent, underlyingNode)
