package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.Duration
import kotlin.Boolean

public abstract class ApplicationLogging(
  retentionPeriod: Duration,
  enabled: Boolean,
  monitoringEnabled: Boolean,
  securityAlertsEnabled: Boolean,
  loggingService: LoggingService,
  underlyingNode: Node,
) : Logging(retentionPeriod, enabled, monitoringEnabled, securityAlertsEnabled, loggingService,
    underlyingNode)
