package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.String

public abstract class AtRestEncryption(
  algorithm: String,
  enabled: Boolean,
  keyUrl: String,
  underlyingNode: Node,
) : Confidentiality(underlyingNode)
