package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.String

public abstract class AtRestEncryption(
  public val algorithm: String,
  public val enabled: Boolean,
  public val keyUrl: String,
  basedOn: Cipher,
  secret: Secret,
  underlyingNode: Node,
) : Encryption(basedOn, secret, underlyingNode)
