package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class Attestation(
  public val enabled: Boolean,
  underlyingNode: Node,
) : Integrity(underlyingNode)
