package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class Authenticity(
  public val contextIsChecked: Boolean,
  underlyingNode: Node,
) : SecurityFeature(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is Authenticity &&
              super.equals(other) &&
              other.contextIsChecked == this.contextIsChecked

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              contextIsChecked,
          )
}
