package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.Operation
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Abstract base class for all authentication operations.
 */
public abstract class AuthenticationOperation(
  public val linkedConcept: Authenticity,
  concept: Concept,
  underlyingNode: Node,
) : Operation(concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is AuthenticationOperation &&
              super.equals(other) &&
              other.linkedConcept == this.linkedConcept

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              linkedConcept,
          )
}
