package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an authentication operation.
 */
public abstract class Authenticate(
  public val credential: Credential?,
  linkedConcept: Authenticity?,
  concept: Concept?,
  underlyingNode: Node?,
) : AuthenticationOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is Authenticate &&
              super.equals(other) &&
              other.credential == this.credential

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              credential,
          )
}
