package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.Duration
import kotlin.Boolean

public abstract class AutomaticUpdates(
  enabled: Boolean,
  interval: Duration,
  securityOnly: Boolean,
  underlyingNode: Node,
) : Integrity(underlyingNode)
