package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.time.Duration
import kotlin.Boolean

public abstract class Backup(
  retentionPeriod: Duration,
  interval: Duration,
  enabled: Boolean,
  transportEncryption: Boolean,
  storage: Storage,
) : Availability()
