package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.Duration
import kotlin.Boolean

public abstract class Backup(
  enabled: Boolean,
  interval: Duration,
  retentionPeriod: Duration,
  storage: Storage,
  transportEncryption: Boolean,
  underlyingNode: Node,
) : Availability(underlyingNode)
