package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.Operation
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class BlockStorageOperation(
  public val linkedConcept: BlockStorage?,
  concept: Concept?,
  underlyingNode: Node?,
) : Operation(concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is BlockStorageOperation &&
              super.equals(other) &&
              other.linkedConcept == this.linkedConcept

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              linkedConcept,
          )
}
