package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class BlockStorage(
  atRestEncryption: Boolean,
  backups: Backup,
  activityLogging: ActivityLogging,
  immutability: Immutability,
  resourceLogging: ResourceLogging,
  internetAccessibleEndpoint: Boolean,
  redundancies: Redundancy,
  loggings: Logging,
  geoLocation: GeoLocation,
  usageStatistics: UsageStatistics,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
) : Storage(atRestEncryption, backups, activityLogging, immutability, resourceLogging,
    internetAccessibleEndpoint, redundancies, loggings, geoLocation, usageStatistics, raw,
    creation_time, labels, name, description, id, parent)
