package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class CertificateBasedAuthentication(
  public val enabled: Boolean?,
  contextIsChecked: Boolean?,
  underlyingNode: Node?,
) : Authenticity(contextIsChecked, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is CertificateBasedAuthentication &&
              super.equals(other) &&
              other.enabled == this.enabled

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              enabled,
          )
}
