package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Certificate(
  expirationDate: ZonedDateTime,
  notBeforeDate: ZonedDateTime,
  enabled: Boolean,
  isManaged: Boolean,
  usedByMultiple: Infrastructure,
  internetAccessibleEndpoint: Boolean,
  redundancies: Redundancy,
  loggings: Logging,
  geoLocation: GeoLocation,
  usageStatistics: UsageStatistics,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
) : Credential(expirationDate, notBeforeDate, enabled, isManaged, usedByMultiple,
    internetAccessibleEndpoint, redundancies, loggings, geoLocation, usageStatistics, raw,
    creation_time, labels, name, description, id, parent)
