package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class CheckAccess(
  linkedConcept: ProtectedAsset,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : ProtectedAssetOperation(linkedConcept, codeRegion, underlyingNode)
