package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class CheckAccess(
  linkedConcept: ProtectedAsset,
  concept: Concept,
  underlyingNode: Node,
) : ProtectedAssetOperation(linkedConcept, concept, underlyingNode)
