package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class CipherSuite(
  sessionCipher: String,
  macAlgorithm: String,
  keyExchangeAlgorithm: String,
  authenticationMechanism: String,
  underlyingNode: Node,
) : Functionality(underlyingNode)
