package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Int
import kotlin.String

/**
 * Represents a cipher suite. E.g. `AES-XTS-plain64`.
 */
public abstract class Cipher(
  public val blockSize: Int,
  public val keySize: Int,
  name: String,
  underlyingNode: Node,
) : Functionality(underlyingNode)
