package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String
import kotlin.collections.MutableList

public abstract class CipherSuite(
  public val authenticationMechanism: String,
  public val keyExchangeAlgorithm: String,
  public val macAlgorithm: String,
  public val ciphers: MutableList<Cipher>,
  underlyingNode: Node,
) : Functionality(underlyingNode)
