package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Int
import kotlin.String

public abstract class CodeRegion(
  code: String,
  endColumn: Int,
  endLine: Int,
  `file`: String,
  startColumn: Int,
  startLine: Int,
  underlyingNode: Node,
) : Functionality(underlyingNode)
