package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Int
import kotlin.String

public abstract class CodeRegion(
  code: String,
  public val endColumn: Int,
  public val endLine: Int,
  public val `file`: String,
  public val startColumn: Int,
  public val startLine: Int,
  underlyingNode: Node,
) : Functionality(underlyingNode)
