package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Component(
  libraries: Library,
  codeRepository: CodeRepository,
  functionalities: Functionality,
  codeModules: CodeModule,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
  underlyingNode: Node,
) : Code(codeRepository, functionalities, codeModules, raw, creation_time, labels, name,
    description, id, parent, underlyingNode)
