package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

/**
 * Represents a group of configuration values within one [conf]. Depending on the type of
 * configuration data structure, there might only be one group (e.g., a \"default\" one), or there
 * might be several groups. For example, when loading a config from an INI file, each section would be
 * mapped to a [ConfigurationGroup], and each key-value pair would be mapped to an
 * [ConfigurationOption] within this group.
 */
public abstract class ConfigurationGroup(
  public val configuration: Configuration,
  public val configurationOptions: MutableList<ConfigurationOption>,
  dataLocation: DataLocation,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Data(dataLocation, creation_time, description, labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
