package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Container(
  image: Image,
  networkInterfaces: NetworkInterface,
  encryptionInUse: EncryptionInUse,
  remoteAttestation: RemoteAttestation,
  resourceLogging: ResourceLogging,
  internetAccessibleEndpoint: Boolean,
  redundancies: Redundancy,
  loggings: Logging,
  geoLocation: GeoLocation,
  usageStatistics: UsageStatistics,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
) : Compute(networkInterfaces, encryptionInUse, remoteAttestation, resourceLogging,
    internetAccessibleEndpoint, redundancies, loggings, geoLocation, usageStatistics, raw,
    creation_time, labels, name, description, id, parent)
