package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class CreateSecret(
  linkedConcept: Secret,
  concept: Concept,
  underlyingNode: Node,
) : SecretOperation(linkedConcept, concept, underlyingNode)
