package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class CreateSecret(
  linkedConcept: Secret,
  underlyingNode: Node?,
) : SecretOperation(linkedConcept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is CreateSecret &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
