package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import kotlin.Boolean
import kotlin.String

public abstract class CryptographicHash(
  algorithm: String,
  usesSalt: Boolean,
  linkedConcept: Confidentiality,
  concept: Concept,
  underlyingNode: Node,
) : CryptographicOperation(linkedConcept, concept, underlyingNode)
