package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.Boolean
import kotlin.String

public abstract class CryptographicHash(
  algorithm: String,
  usesSalt: Boolean,
  codeRegion: CodeRegion,
) : CryptographicOperation(codeRegion)
