package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.String

public abstract class CryptographicHash(
  algorithm: String,
  usesSalt: Boolean,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : CryptographicOperation(codeRegion, underlyingNode)
