package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.String

public abstract class CustomerKeyEncryption(
  enabled: Boolean,
  algorithm: String,
  keyUrl: String,
  underlyingNode: Node,
) : AtRestEncryption(enabled, algorithm, keyUrl, underlyingNode)
