package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.Boolean
import kotlin.String

public abstract class CustomerKeyEncryption(
  enabled: Boolean,
  algorithm: String,
  keyUrl: String,
) : AtRestEncryption(enabled, algorithm, keyUrl)
