package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.Operation
import java.util.List
import kotlin.String

public abstract class DatabaseOperation(
  calls: List<String>,
  databaseService: DatabaseService,
  storage: DatabaseStorage,
  concept: Concept,
  underlyingNode: Node,
) : Operation(concept, underlyingNode)
