package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.List
import kotlin.String

public abstract class DatabaseConnect(
  calls: List<String>,
  storage: DatabaseStorage,
  databaseService: DatabaseService,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : DatabaseOperation(calls, storage, databaseService, codeRegion, underlyingNode)
