package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.util.List
import kotlin.String

public abstract class DatabaseConnect(
  calls: List<String>,
  storage: DatabaseStorage,
  databaseService: DatabaseService,
  codeRegion: CodeRegion,
) : DatabaseOperation(calls, storage, databaseService, codeRegion)
