package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.List
import kotlin.String

public abstract class DatabaseOperation(
  calls: List<String>,
  databaseService: DatabaseService,
  storage: DatabaseStorage,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : Operation(codeRegion, underlyingNode)
