package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.List
import kotlin.Boolean
import kotlin.String

public abstract class DatabaseQuery(
  modify: Boolean,
  calls: List<String>,
  databaseService: DatabaseService,
  storage: DatabaseStorage,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : DatabaseOperation(calls, databaseService, storage, codeRegion, underlyingNode)
