package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.util.List
import kotlin.String

public abstract class DatabaseOperation(
  calls: List<String>,
  storage: DatabaseStorage,
  databaseService: DatabaseService,
  codeRegion: CodeRegion,
) : Operation(codeRegion)
