package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Array
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

/**
 * This class represents a database service. For example, a postgres SQL server would be modelled as
 * a database service (with a host and IP) and the individual tables or collections would be modelled
 * as a DatabaseStorage entity.
 */
public abstract class DatabaseService(
  public val anomalyDetections: AnomalyDetection,
  public val httpEndpoint: HttpEndpoint,
  public val malwareProtection: MalwareProtection,
  activityLogging: ActivityLogging,
  storage: MutableList<Storage>,
  ips: Array<String>,
  ports: Array<Short>,
  authenticity: Boolean,
  computes: MutableList<Compute>,
  serviceMetadataDocument: ServiceMetadataDocument,
  transportEncryption: TransportEncryption,
  internetAccessibleEndpoint: Boolean,
  geoLocation: GeoLocation,
  loggings: MutableList<Logging>,
  redundancies: Redundancy,
  usageStatistics: UsageStatistics,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : StorageService(activityLogging, storage, ips, ports, authenticity, computes,
    serviceMetadataDocument, transportEncryption, internetAccessibleEndpoint, geoLocation, loggings,
    redundancies, usageStatistics, creation_time, description, labels, name, raw, parent,
    underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
