package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

/**
 * path: Describes either local path or path in URL format
 */
public abstract class DataLocation(
  public val path: String,
  public val storage: Storage,
  underlyingNode: Node,
) : Functionality(underlyingNode)
