package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.List
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String

public abstract class DatabaseQuery(
  public val modify: Boolean,
  calls: List<String>,
  databaseService: DatabaseService,
  storage: DatabaseStorage,
  concept: Concept,
  underlyingNode: Node,
) : DatabaseOperation(calls, databaseService, storage, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is DatabaseQuery &&
              super.equals(other) &&
              other.modify == this.modify

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              modify,
          )
}
