package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class DDoSProtection(
  underlyingNode: Node,
) : Availability(underlyingNode)
