package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class DeAllocate(
  linkedConcept: Memory,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : MemoryOperation(linkedConcept, codeRegion, underlyingNode)
