package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class DeAllocate(
  linkedConcept: Memory,
  concept: Concept,
  underlyingNode: Node,
) : MemoryOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is DeAllocate &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
