package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class DeAllocate(
  linkedConcept: Memory,
  concept: Concept,
  underlyingNode: Node,
) : MemoryOperation(linkedConcept, concept, underlyingNode)
