package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class Decryption(
  algorithm: String,
  secret: Secret,
  linkedConcept: Cipher,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : CipherOperation(linkedConcept, codeRegion, underlyingNode)
