package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.String

public abstract class Decryption(
  algorithm: String,
  codeRegion: CodeRegion,
) : CryptographicOperation(codeRegion)
