package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class Decryption(
  algorithm: String,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : CryptographicOperation(codeRegion, underlyingNode)
