package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.String

public abstract class DiskEncryption(
  public val target: BlockStorage,
  algorithm: String,
  enabled: Boolean,
  keyUrl: String,
  basedOn: Cipher,
  secret: Secret,
  underlyingNode: Node,
) : AtRestEncryption(algorithm, enabled, keyUrl, basedOn, secret, underlyingNode)
