package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

/**
 * DataLocation: Describes the location as local or remote location
 */
public abstract class Document(
  public val filetype: String?,
  public val documentChecksums: MutableList<DocumentChecksum?>,
  public val documentSignatures: MutableList<DocumentSignature?>,
  public val securityFeatures: MutableList<SecurityFeature?>,
  public val validatedBy: SchemaValidation?,
  dataLocation: DataLocation?,
  creation_time: ZonedDateTime?,
  description: String?,
  labels: MutableMap<String, String>?,
  name: String?,
  raw: String?,
  parent: Resource?,
  underlyingNode: Node?,
) : Data(dataLocation, creation_time, description, labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }

  override fun equals(other: Any?): Boolean = other is Document &&
              super.equals(other) &&
              other.filetype == this.filetype &&
              other.documentChecksums == this.documentChecksums &&
              other.documentSignatures == this.documentSignatures &&
              other.securityFeatures == this.securityFeatures &&
              other.validatedBy == this.validatedBy

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              filetype,
              documentChecksums,
              documentSignatures,
              securityFeatures,
              validatedBy,
          )
}
