package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class DocumentSignature(
  public val algorithm: String,
  public val errors: Error,
  underlyingNode: Node,
) : Integrity(underlyingNode)
