package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

/**
 * Represents an entity that loads a piece of code dynamically during runtime. Examples include a
 * class loader in Java, loading shared library code in C++. Interpreters, such as Python can also load
 * code dynamically during runtime.
 */
public abstract class DynamicLoading(
  underlyingNode: Node,
) : Functionality(underlyingNode)
