package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an entity that loads a piece of code dynamically during runtime. Examples include a
 * class loader in Java, loading shared library code in C++. Interpreters, such as Python can also load
 * code dynamically during runtime.
 */
public abstract class DynamicLoading(
  underlyingNode: Node?,
) : Functionality(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is DynamicLoading &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
