package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture

public abstract class DynamicLoadingOperation(
  operatingSystemArchitecture: OperatingSystemArchitecture,
  linkedConcept: Memory,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : MemoryOperation(linkedConcept, codeRegion, underlyingNode)
