package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * This represents an encryption.
 */
public abstract class Encryption(
  public val basedOn: Cipher,
  public val secret: Secret,
  underlyingNode: Node,
) : Confidentiality(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is Encryption &&
              super.equals(other) &&
              other.basedOn == this.basedOn &&
              other.secret == this.secret

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              basedOn,
              secret,
          )
}
