package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class Encryption(
  public val basedOn: Cipher,
  public val secret: Secret,
  underlyingNode: Node,
) : Confidentiality(underlyingNode)
