package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class EncryptionOperation(
  algorithm: String,
  linkedConcept: Encryption,
  secret: Secret,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : Operation(codeRegion, underlyingNode)
