package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.Operation
import kotlin.String

public abstract class EncryptionOperation(
  algorithm: String,
  linkedConcept: Encryption,
  secret: Secret,
  concept: Concept,
  underlyingNode: Node,
) : Operation(concept, underlyingNode)
