package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class EqualityCheck(
  leftPrincipal: Principal,
  rightPrincipal: Principal,
  linkedConcept: Policy,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : PolicyOperation(linkedConcept, codeRegion, underlyingNode)
