package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an operation that checks whether two principals are equal.
 */
public abstract class EqualityCheck(
  public val leftPrincipal: Principal?,
  public val rightPrincipal: Principal?,
  linkedConcept: Policy?,
  concept: Concept?,
  underlyingNode: Node?,
) : PolicyOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is EqualityCheck &&
              super.equals(other) &&
              other.leftPrincipal == this.leftPrincipal &&
              other.rightPrincipal == this.rightPrincipal

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              leftPrincipal,
              rightPrincipal,
          )
}
