package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class EqualityCheck(
  leftPrincipal: Principal,
  rightPrincipal: Principal,
  linkedConcept: Policy,
  concept: Concept,
  underlyingNode: Node,
) : PolicyOperation(linkedConcept, concept, underlyingNode)
