package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class Error(
  message: String,
  underlyingNode: Node,
) : Functionality(underlyingNode)
