package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.Operation
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an exit operation that is part of a [Boundary]. This operation is used to define the
 * point at which data leaves the boundary.
 */
public abstract class ExitBoundaryOperation(
  public val linkedConcept: Boundary,
  concept: Concept,
  underlyingNode: Node,
) : Operation(concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is ExitBoundaryOperation &&
              super.equals(other) &&
              other.linkedConcept == this.linkedConcept

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              linkedConcept,
          )
}
