package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class ExplainableResults(
  underlyingNode: Node?,
) : Reliability(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is ExplainableResults &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
