package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class ExplainableResults(
  underlyingNode: Node,
) : Reliability(underlyingNode)
