package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class FileStorage(
  publicAccess: Boolean,
  activityLogging: ActivityLogging,
  atRestEncryption: Boolean,
  backups: Backup,
  immutability: Immutability,
  resourceLogging: ResourceLogging,
  internetAccessibleEndpoint: Boolean,
  geoLocation: GeoLocation,
  loggings: Logging,
  redundancies: Redundancy,
  usageStatistics: UsageStatistics,
  creation_time: ZonedDateTime,
  description: String,
  id: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Storage(activityLogging, atRestEncryption, backups, immutability, resourceLogging,
    internetAccessibleEndpoint, geoLocation, loggings, redundancies, usageStatistics, creation_time,
    description, id, labels, name, raw, parent, underlyingNode)
