package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class FileOperation(
  linkedConcept: File,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : Operation(codeRegion, underlyingNode)
