package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Array
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.collections.MutableMap

public abstract class FunctionService(
  functions: Function,
  ips: Array<String>,
  ports: Array<Short>,
  authenticity: Boolean,
  computes: Compute,
  serviceMetadataDocument: ServiceMetadataDocument,
  transportEncryption: TransportEncryption,
  internetAccessibleEndpoint: Boolean,
  geoLocation: GeoLocation,
  loggings: Logging,
  redundancies: Redundancy,
  usageStatistics: UsageStatistics,
  creation_time: ZonedDateTime,
  description: String,
  id: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : NetworkService(ips, ports, authenticity, computes, serviceMetadataDocument, transportEncryption,
    internetAccessibleEndpoint, geoLocation, loggings, redundancies, usageStatistics, creation_time,
    description, id, labels, name, raw, parent, underlyingNode)
