package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableMap

public abstract class GenericDocument(
  filetype: String,
  validatedBy: SchemaValidation,
  documentChecksums: DocumentChecksum,
  securityFeatures: SecurityFeature,
  documentSignatures: DocumentSignature,
  dataLocation: DataLocation,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
  underlyingNode: Node,
) : Document(filetype, validatedBy, documentChecksums, securityFeatures, documentSignatures,
    dataLocation, raw, creation_time, labels, name, description, id, parent, underlyingNode)
