package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * An operation that retrieves a secret from a (remote) location. This can be a local keystore, a
 * remote key server or a hardware device such as a TPM or HSM.
 */
public abstract class GetSecret(
  linkedConcept: Secret,
  concept: Concept,
  underlyingNode: Node,
) : SecretOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is GetSecret &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
