package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class GetSecret(
  linkedConcept: Secret,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : SecretOperation(linkedConcept, codeRegion, underlyingNode)
