package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class HttpRequestHandler(
  public val path: String,
  public val application: Application,
  public val httpEndpoints: HttpEndpoint,
  underlyingNode: Node,
) : Http(underlyingNode)
