package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import kotlin.String

public abstract class HttpRequest(
  call: String,
  reqBody: String,
  httpEndpoint: HttpEndpoint,
  linkedConcept: HttpClient,
  concept: Concept,
  underlyingNode: Node,
) : HttpClientOperation(linkedConcept, concept, underlyingNode)
