package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String

public abstract class HttpRequest(
  public val call: String?,
  public val reqBody: String?,
  public val httpEndpoint: HttpEndpoint?,
  linkedConcept: HttpClient?,
  concept: Concept?,
  underlyingNode: Node?,
) : HttpClientOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is HttpRequest &&
              super.equals(other) &&
              other.call == this.call &&
              other.reqBody == this.reqBody &&
              other.httpEndpoint == this.httpEndpoint

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              call,
              reqBody,
              httpEndpoint,
          )
}
