package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * HTTP Client.
 */
public abstract class HttpClient(
  public val isTLS: Boolean?,
  public val authenticity: Authenticity?,
  underlyingNode: Node?,
) : Http(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is HttpClient &&
              super.equals(other) &&
              other.isTLS == this.isTLS &&
              other.authenticity == this.authenticity

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              isTLS,
              authenticity,
          )
}
