package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an abstract concept of request context. This usually holds the contextual information
 * of a specific HTTP request.
 */
public abstract class HttpRequestContext(
  underlyingNode: Node?,
) : Http(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is HttpRequestContext &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
