package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class HttpClientOperation(
  linkedConcept: HttpClient,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : Operation(codeRegion, underlyingNode)
