package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.String

public abstract class HttpRequest(
  reqBody: String,
  call: String,
  httpEndpoint: HttpEndpoint,
  codeRegion: CodeRegion,
) : Operation(codeRegion)
