package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class HttpEndpoint(
  handler: String,
  method: String,
  path: String,
  url: String,
  authenticity: Authenticity,
  proxyTarget: HttpEndpoint,
  transportEncryption: TransportEncryption,
  underlyingNode: Node,
) : Functionality(underlyingNode)
