package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class HttpRequestHandler(
  path: String,
  application: Application,
  httpEndpoints: HttpEndpoint,
  underlyingNode: Node,
) : Functionality(underlyingNode)
