package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.String

public abstract class HttpRequestHandler(
  path: String,
  application: Application,
  httpEndpoints: HttpEndpoint,
) : Functionality()
