package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

/**
 * Abstract class for all HTTP related functionalities.
 */
public abstract class Http(
  underlyingNode: Node,
) : Functionality(underlyingNode)
