package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class HttpServer(
  public val httpRequestHandler: HttpRequestHandler,
  underlyingNode: Node,
) : Framework(underlyingNode)
