package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.Operation

public abstract class HttpClientOperation(
  linkedConcept: HttpClient,
  concept: Concept,
  underlyingNode: Node,
) : Operation(concept, underlyingNode)
