package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class HttpClient(
  public val isTLS: Boolean,
  public val authenticity: Authenticity,
  underlyingNode: Node,
) : Http(underlyingNode)
