package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class HttpClient(
  isTLS: Boolean,
  authenticity: Authenticity,
  underlyingNode: Node,
) : Http(underlyingNode)
