package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Identity(
  lastActivity: ZonedDateTime,
  privileged: Boolean,
  disablePasswordPolicy: Boolean,
  enforceMFA: Boolean,
  loginDefenderEnabled: Boolean,
  activated: Boolean,
  authenticity: Authenticity,
  authorization: Authorization,
  internetAccessibleEndpoint: Boolean,
  redundancies: Redundancy,
  loggings: Logging,
  geoLocation: GeoLocation,
  usageStatistics: UsageStatistics,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
  underlyingNode: Node,
) : Identifiable(activated, authenticity, authorization, internetAccessibleEndpoint, redundancies,
    loggings, geoLocation, usageStatistics, raw, creation_time, labels, name, description, id,
    parent, underlyingNode)
