package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Identity(
  public val disablePasswordPolicy: Boolean,
  public val enforceMFA: Boolean,
  public val lastActivity: ZonedDateTime,
  public val loginDefenderEnabled: Boolean,
  public val privileged: Boolean,
  activated: Boolean,
  authenticity: Authenticity,
  authorization: Authorization,
  internetAccessibleEndpoint: Boolean,
  geoLocation: GeoLocation,
  loggings: Logging,
  redundancies: Redundancy,
  usageStatistics: UsageStatistics,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Identifiable(activated, authenticity, authorization, internetAccessibleEndpoint, geoLocation,
    loggings, redundancies, usageStatistics, creation_time, description, labels, name, raw, parent,
    underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
