package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

/**
 * internetAccessibleEndpoint: Is true if the management API endpoint is reachable from everywhere.
 * Access controls can still apply.
 */
public abstract class Infrastructure(
  public val internetAccessibleEndpoint: Boolean,
  public val geoLocation: GeoLocation,
  public val loggings: MutableList<Logging>,
  public val redundancies: Redundancy,
  public val usageStatistics: UsageStatistics,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Resource(creation_time, description, labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }

  override fun equals(other: Any?): Boolean = other is Infrastructure &&
              super.equals(other) &&
              other.internetAccessibleEndpoint == this.internetAccessibleEndpoint &&
              other.geoLocation == this.geoLocation &&
              other.loggings == this.loggings &&
              other.redundancies == this.redundancies &&
              other.usageStatistics == this.usageStatistics

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              internetAccessibleEndpoint,
              geoLocation,
              loggings,
              redundancies,
              usageStatistics,
          )
}
