package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class IssueJwt(
  linkedConcept: Authenticity,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : AuthenticationOperation(linkedConcept, codeRegion, underlyingNode)
