package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class IssueJwt(
  linkedConcept: Authenticity,
  concept: Concept,
  underlyingNode: Node,
) : AuthenticationOperation(linkedConcept, concept, underlyingNode)
