package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an operation to issue a new JWT token.
 */
public abstract class IssueJwt(
  linkedConcept: Authenticity,
  concept: Concept,
  underlyingNode: Node,
) : AuthenticationOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is IssueJwt &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
