package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class JwtAuthentication(
  enabled: Boolean,
  enforced: Boolean,
  token: Token,
  contextIsChecked: Boolean,
  underlyingNode: Node,
) : TokenBasedAuthentication(enabled, enforced, token, contextIsChecked, underlyingNode)
