package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.Boolean
import kotlin.String

public abstract class L3Firewall(
  inbound: Boolean,
  enabled: Boolean,
  restrictedPorts: String,
) : Firewall()
