package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.String

public abstract class L3Firewall(
  inbound: Boolean,
  enabled: Boolean,
  restrictedPorts: String,
  underlyingNode: Node,
) : Firewall(underlyingNode)
