package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an entry point that is triggered if the code is loaded as a (dynamic) library.
 */
public abstract class LibraryEntryPoint(
  target: OperatingSystemArchitecture,
  underlyingNode: Node,
) : LocalEntryPoint(target, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is LibraryEntryPoint &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
