package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Library(
  public val vulnerabilities: Vulnerability,
  libraries: Library,
  codeModules: CodeModule,
  codeRepository: CodeRepository,
  functionalities: Functionality,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Component(libraries, codeModules, codeRepository, functionalities, creation_time, description,
    labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
