package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture

/**
 * Represents an entry point that is triggered if the code is loaded as a (dynamic) library.
 */
public abstract class LibraryEntryPoint(
  target: OperatingSystemArchitecture,
  underlyingNode: Node,
) : LocalEntryPoint(target, underlyingNode)
