package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture

public abstract class LoadSymbol(
  operatingSystemArchitecture: OperatingSystemArchitecture,
  linkedConcept: Memory,
  concept: Concept,
  underlyingNode: Node,
) : DynamicLoadingOperation(operatingSystemArchitecture, linkedConcept, concept, underlyingNode)
