package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture

/**
 * Represents a local entry point into the execution of the program, such as a main function.
 */
public abstract class LocalEntryPoint(
  public val target: OperatingSystemArchitecture,
  underlyingNode: Node,
) : EntryPoint(underlyingNode)
