package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class LocalAttestation(
  enabled: Boolean,
  underlyingNode: Node,
) : Attestation(enabled, underlyingNode)
