package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String

public abstract class LocalDataLocation(
  public val atRestEncryption: AtRestEncryption,
  path: String,
  storage: Storage,
  underlyingNode: Node,
) : DataLocation(path, storage, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is LocalDataLocation &&
              super.equals(other) &&
              other.atRestEncryption == this.atRestEncryption

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              atRestEncryption,
          )
}
