package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture

public abstract class LocalEntryPoint(
  target: OperatingSystemArchitecture,
  underlyingNode: Node,
) : EntryPoint(underlyingNode)
