package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class LocalRedundancy(
  geoLocations: GeoLocation,
  underlyingNode: Node,
) : Redundancy(geoLocations, underlyingNode)
