package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents a local entry point into the execution of the program, such as a main function.
 */
public abstract class LocalEntryPoint(
  public val target: OperatingSystemArchitecture?,
  underlyingNode: Node?,
) : EntryPoint(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is LocalEntryPoint &&
              super.equals(other) &&
              other.target == this.target

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              target,
          )
}
