package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.collections.MutableList

public abstract class LocalRedundancy(
  geoLocations: MutableList<GeoLocation?>,
  underlyingNode: Node?,
) : Redundancy(geoLocations, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is LocalRedundancy &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
