package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.String

public abstract class LocalDataLocation(
  atRestEncryption: AtRestEncryption,
  path: String,
  storage: Storage,
) : DataLocation(path, storage)
