package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

public abstract class LogDocument(
  filetype: String,
  documentChecksums: MutableList<DocumentChecksum>,
  documentSignatures: MutableList<DocumentSignature>,
  securityFeatures: MutableList<SecurityFeature>,
  validatedBy: SchemaValidation,
  dataLocation: DataLocation,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Document(filetype, documentChecksums, documentSignatures, securityFeatures, validatedBy,
    dataLocation, creation_time, description, labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
