package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class LogGet(
  linkedConcept: Logging,
  concept: Concept,
  underlyingNode: Node,
) : LogOperation(linkedConcept, concept, underlyingNode)
