package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.Duration
import kotlin.Boolean
import kotlin.String

public abstract class Logging(
  public val enabled: Boolean,
  public val monitoringEnabled: Boolean,
  name: String,
  public val retentionPeriod: Duration,
  public val securityAlertsEnabled: Boolean,
  public val loggingService: LoggingService,
  underlyingNode: Node,
) : Auditing(underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
