package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class LogGet(
  linkedConcept: Logging,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : LogOperation(linkedConcept, codeRegion, underlyingNode)
