package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.Duration
import kotlin.Boolean

public abstract class Logging(
  retentionPeriod: Duration,
  enabled: Boolean,
  monitoringEnabled: Boolean,
  securityAlertsEnabled: Boolean,
  loggingService: LoggingService,
  underlyingNode: Node,
) : Auditing(underlyingNode)
