package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * A log get operation e.g. `logging.getLogger(\"...\")`.
 */
public abstract class LogGet(
  linkedConcept: Logging,
  underlyingNode: Node?,
) : LogOperation(linkedConcept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is LogGet &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
