package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String

/**
 * A log write operation e.g. `loggint.warn(\"...\")`.
 */
public abstract class LogWrite(
  public val logLevel: String?,
  linkedConcept: Logging?,
  concept: Concept?,
  underlyingNode: Node?,
) : LogOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is LogWrite &&
              super.equals(other) &&
              other.logLevel == this.logLevel

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              logLevel,
          )
}
