package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import kotlin.String

public abstract class LogWrite(
  logLevel: String,
  linkedConcept: Logging,
  concept: Concept,
  underlyingNode: Node,
) : LogOperation(linkedConcept, concept, underlyingNode)
