package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Int
import kotlin.String
import kotlin.collections.MutableMap

public abstract class MachineLearningDataset(
  size: Int,
  type: String,
  dataLocation: DataLocation,
  creation_time: ZonedDateTime,
  description: String,
  id: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : MachineLearning(dataLocation, creation_time, description, id, labels, name, raw, parent,
    underlyingNode)
