package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Float
import kotlin.String
import kotlin.collections.MutableMap

public abstract class MachineLearningModel(
  explainability: Float,
  privacyLevel: Float,
  poisonLevel: Float,
  robustness: Float,
  adv_robustness: Float,
  privacyLabel: Float,
  vulnerabilities: Vulnerability,
  dataLocation: DataLocation,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
  underlyingNode: Node,
) : MachineLearning(dataLocation, raw, creation_time, labels, name, description, id, parent,
    underlyingNode)
