package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture

public abstract class Main(
  target: OperatingSystemArchitecture,
  underlyingNode: Node,
) : LocalEntryPoint(target, underlyingNode)
