package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.arch.OperatingSystemArchitecture
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * The main function of a program.
 */
public abstract class Main(
  target: OperatingSystemArchitecture,
  underlyingNode: Node,
) : LocalEntryPoint(target, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is Main &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
