package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.String

public abstract class ManagedKeyEncryption(
  algorithm: String,
  enabled: Boolean,
  keyUrl: String,
  underlyingNode: Node,
) : AtRestEncryption(algorithm, enabled, keyUrl, underlyingNode)
