package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.Boolean

public abstract class MultiFactorAuthentiation(
  authenticities: Authenticity,
  contextIsChecked: Boolean,
) : Authenticity(contextIsChecked)
