package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class MultiFactorAuthentiation(
  public val authenticities: Authenticity,
  contextIsChecked: Boolean,
  underlyingNode: Node,
) : Authenticity(contextIsChecked, underlyingNode)
