package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class NoAuthentication(
  contextIsChecked: Boolean,
  underlyingNode: Node,
) : Authenticity(contextIsChecked, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is NoAuthentication &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
