package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.String

public abstract class ObjectStorageRequest(
  source: String,
  objectStorage: ObjectStorage,
  codeRegion: CodeRegion,
) : Operation(codeRegion)
