package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Operation
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String

public abstract class ObjectStorageRequest(
  public val source: String?,
  public val objectStorage: ObjectStorage?,
  public val linkedConcept: Storage,
  underlyingNode: Node?,
) : Operation(linkedConcept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is ObjectStorageRequest &&
              super.equals(other) &&
              other.source == this.source &&
              other.objectStorage == this.objectStorage

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              source,
              objectStorage,
          )
}
