package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

/**
 * publicAccess: Means if access to the actual object is public or not
 */
public abstract class ObjectStorage(
  public val publicAccess: Boolean?,
  activityLogging: ActivityLogging?,
  atRestEncryption: Boolean?,
  backups: MutableList<Backup?>,
  immutability: Immutability?,
  resourceLogging: ResourceLogging?,
  internetAccessibleEndpoint: Boolean?,
  geoLocation: GeoLocation?,
  loggings: MutableList<Logging?>,
  redundancies: Redundancy?,
  usageStatistics: UsageStatistics?,
  creation_time: ZonedDateTime?,
  description: String?,
  labels: MutableMap<String, String>?,
  name: String?,
  raw: String?,
  parent: Resource?,
  underlyingNode: Node?,
) : Storage(activityLogging, atRestEncryption, backups, immutability, resourceLogging,
    internetAccessibleEndpoint, geoLocation, loggings, redundancies, usageStatistics, creation_time,
    description, labels, name, raw, parent, underlyingNode) {
  init {
    name?.let { this.name = Name(localName = it) }
  }

  override fun equals(other: Any?): Boolean = other is ObjectStorage &&
              super.equals(other) &&
              other.publicAccess == this.publicAccess

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              publicAccess,
          )
}
