package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.Duration
import kotlin.Boolean

public abstract class OSLogging(
  enabled: Boolean,
  monitoringEnabled: Boolean,
  retentionPeriod: Duration,
  securityAlertsEnabled: Boolean,
  loggingService: LoggingService,
  underlyingNode: Node,
) : Logging(enabled, monitoringEnabled, retentionPeriod, securityAlertsEnabled, loggingService,
    underlyingNode)
