package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class OTPBasedAuthentication(
  activated: Boolean,
  contextIsChecked: Boolean,
  underlyingNode: Node,
) : Authenticity(contextIsChecked, underlyingNode)
