package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class OTPBasedAuthentication(
  public val activated: Boolean,
  contextIsChecked: Boolean,
  underlyingNode: Node,
) : Authenticity(contextIsChecked, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is OTPBasedAuthentication &&
              super.equals(other) &&
              other.activated == this.activated

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              activated,
          )
}
