package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.Boolean

public abstract class PasswordBasedAuthentication(
  activated: Boolean,
  contextIsChecked: Boolean,
) : Authenticity(contextIsChecked)
