package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

/**
 * Represents a principal that is allowed to access a resource. This can for example be a (structure
 * representing) a user or a group of users.
 */
public abstract class Principal(
  underlyingNode: Node,
) : Functionality(underlyingNode)
