package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class ProtectedAsset(
  public val policies: Policy,
  public val protects: Resource,
  underlyingNode: Node,
) : Functionality(underlyingNode)
