package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.collections.MutableList

/**
 * Represents an asset that is protected by a policy. This can be an in-memory data structure, a
 * file, a database, or any other resource that requires access control.
 */
public abstract class ProtectedAsset(
  public val policies: MutableList<Policy>,
  public val protects: Resource,
  underlyingNode: Node,
) : Functionality(underlyingNode)
