package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class ProtectedAsset(
  policies: Policy,
  protects: Resource,
  underlyingNode: Node,
) : Functionality(underlyingNode)
