package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class ProtectedAssetOperation(
  linkedConcept: ProtectedAsset,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : Operation(codeRegion, underlyingNode)
