package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class ProvideConfigurationGroup(
  configurationGroup: ConfigurationGroup,
  configurationGroupSource: ConfigurationGroupSource,
  linkedConcept: Configuration,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : ConfigurationOperation(linkedConcept, codeRegion, underlyingNode)
