package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class ProvideConfiguration(
  public val configuration: Configuration,
  public val configurationSource: ConfigurationSource,
  linkedConcept: Configuration,
  concept: Concept,
  underlyingNode: Node,
) : ConfigurationOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is ProvideConfiguration &&
              super.equals(other) &&
              other.configuration == this.configuration &&
              other.configurationSource == this.configurationSource

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              configuration,
              configurationSource,
          )
}
