package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class ProvideConfigurationOption(
  public val configurationOption: ConfigurationOption,
  public val configurationOptionSource: ConfigurationOptionSource,
  linkedConcept: Configuration,
  concept: Concept,
  underlyingNode: Node,
) : ConfigurationOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is ProvideConfigurationOption &&
              super.equals(other) &&
              other.configurationOption == this.configurationOption &&
              other.configurationOptionSource == this.configurationOptionSource

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              configurationOption,
              configurationOptionSource,
          )
}
