package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class ProvideConfiguration(
  configuration: Configuration,
  configurationSource: ConfigurationSource,
  linkedConcept: Configuration,
  concept: Concept,
  underlyingNode: Node,
) : ConfigurationOperation(linkedConcept, concept, underlyingNode)
