package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Float
import kotlin.Int
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

public abstract class QPU(
  public val OneQubitErrorRate: Float?,
  public val SpamErrorRate: Float?,
  public val TwoQubitErrorRate: Float?,
  public val errorCorrectionEnabled: Boolean?,
  encryptionInUse: EncryptionInUse?,
  networkInterfaces: MutableList<NetworkInterface?>,
  remoteAttestation: RemoteAttestation?,
  resourceLogging: ResourceLogging?,
  internetAccessibleEndpoint: Boolean?,
  geoLocation: GeoLocation?,
  loggings: MutableList<Logging?>,
  redundancies: Redundancy?,
  usageStatistics: UsageStatistics?,
  creation_time: ZonedDateTime?,
  description: String?,
  labels: MutableMap<String, String>?,
  name: String?,
  raw: String?,
  parent: Resource?,
  underlyingNode: Node?,
) : Compute(encryptionInUse, networkInterfaces, remoteAttestation, resourceLogging,
    internetAccessibleEndpoint, geoLocation, loggings, redundancies, usageStatistics, creation_time,
    description, labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }

  override fun equals(other: Any?): Boolean = other is QPU &&
              super.equals(other) &&
              other.OneQubitErrorRate == this.OneQubitErrorRate &&
              other.SpamErrorRate == this.SpamErrorRate &&
              other.TwoQubitErrorRate == this.TwoQubitErrorRate &&
              other.errorCorrectionEnabled == this.errorCorrectionEnabled

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              OneQubitErrorRate,
              SpamErrorRate,
              TwoQubitErrorRate,
              errorCorrectionEnabled,
          )
}
