package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Float

public abstract class RBAC(
  broadAssignments: Float,
  mixedDuties: Float,
  underlyingNode: Node,
) : Authorization(underlyingNode)
