package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Float
import kotlin.Int

public abstract class RBAC(
  public val broadAssignments: Float,
  public val mixedDuties: Float,
  underlyingNode: Node,
) : Authorization(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is RBAC &&
              super.equals(other) &&
              other.broadAssignments == this.broadAssignments &&
              other.mixedDuties == this.mixedDuties

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              broadAssignments,
              mixedDuties,
          )
}
