package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an operation to read a specific configuration group. Often this is done with a member
 * access or a subscript operation on the configuration object, such as`conf.GROUP`
 * or`conf[\"GROUP\"]`.
 */
public abstract class ReadConfigurationGroup(
  public val configurationGroup: ConfigurationGroup?,
  linkedConcept: Configuration,
  underlyingNode: Node?,
) : ConfigurationOperation(linkedConcept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is ReadConfigurationGroup &&
              super.equals(other) &&
              other.configurationGroup == this.configurationGroup

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              configurationGroup,
          )
}
