package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class ReadConfigurationGroup(
  configurationGroup: ConfigurationGroup,
  linkedConcept: Configuration,
  concept: Concept,
  underlyingNode: Node,
) : ConfigurationOperation(linkedConcept, concept, underlyingNode)
