package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.collections.MutableList

public abstract class Redundancy(
  public val geoLocations: MutableList<GeoLocation>,
  underlyingNode: Node,
) : Availability(underlyingNode)
