package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class Redundancy(
  public val geoLocations: GeoLocation,
  underlyingNode: Node,
) : Availability(underlyingNode)
