package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class RegisterHttpEndpoint(
  httpEndpoint: HttpEndpoint,
  linkedConcept: HttpRequestHandler,
  concept: Concept,
  underlyingNode: Node,
) : HttpRequestHandlerOperation(linkedConcept, concept, underlyingNode)
