package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class RegisterConfigurationOption(
  configurationOption: ConfigurationOption,
  linkedConcept: Configuration,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : ConfigurationOperation(linkedConcept, codeRegion, underlyingNode)
