package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class RegisterHttpEndpoint(
  public val httpEndpoint: HttpEndpoint?,
  linkedConcept: HttpRequestHandler?,
  concept: Concept?,
  underlyingNode: Node?,
) : HttpRequestHandlerOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is RegisterHttpEndpoint &&
              super.equals(other) &&
              other.httpEndpoint == this.httpEndpoint

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              httpEndpoint,
          )
}
