package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class RegisterHttpEndpoint(
  httpEndpoint: HttpEndpoint,
  linkedConcept: HttpRequestHandler,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : HttpRequestHandlerOperation(linkedConcept, codeRegion, underlyingNode)
