package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class RegisterConfigurationGroup(
  public val configurationGroup: ConfigurationGroup,
  linkedConcept: Configuration,
  concept: Concept,
  underlyingNode: Node,
) : ConfigurationOperation(linkedConcept, concept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is RegisterConfigurationGroup &&
              super.equals(other) &&
              other.configurationGroup == this.configurationGroup

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              configurationGroup,
          )
}
