/*
 * Copyright (c) 2025, Fraunhofer AISEC. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *                    $$$$$$\  $$$$$$$\   $$$$$$\
 *                   $$  __$$\ $$  __$$\ $$  __$$\
 *                   $$ /  \__|$$ |  $$ |$$ /  \__|
 *                   $$ |      $$$$$$$  |$$ |$$$$\
 *                   $$ |      $$  ____/ $$ |\_$$ |
 *                   $$ |  $$\ $$ |      $$ |  $$ |
 *                   \$$$$$   |$$ |      \$$$$$   |
 *                    \______/ \__|       \______/
 *
 */
package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an operation to register a new [ConfigurationOption]. This is often done with a call,
 * such as `conf.registerOption("option", "defaultValue")`. This might not be necessary for all
 * configuration frameworks, some might allow to directly read the group (via
 * [RegisterConfigurationOption]) without registering it first, or it is done implicitly. When code
 * and configuration is interacting, we expect that the configuration file (such as an INI file)
 * contains the [ConfigurationOption] node and the code contains the [RegisterConfigurationOption]
 * and [ReadConfigurationOption] nodes.
 */
public abstract class RegisterConfigurationOption(
    public val configurationOption: ConfigurationOption?,
    linkedConcept: Configuration,
    underlyingNode: Node?,
) : ConfigurationOperation(linkedConcept, underlyingNode) {
    override fun equals(other: Any?): Boolean =
        other is RegisterConfigurationOption &&
            super.equals(other) &&
            other.configurationOption == this.configurationOption

    override fun hashCode(): Int = Objects.hash(super.hashCode(), configurationOption)
}
