package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.time.ZonedDateTime
import kotlin.Boolean

public abstract class RemoteAttestation(
  creation_time: ZonedDateTime,
  status: Boolean,
  enabled: Boolean,
) : Attestation(enabled)
