package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean

public abstract class RemoteAttestation(
  status: Boolean,
  creation_time: ZonedDateTime,
  enabled: Boolean,
  underlyingNode: Node,
) : Attestation(enabled, underlyingNode)
