package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class RemoteDataLocation(
  authenticity: Authenticity,
  transportEncryption: TransportEncryption,
  path: String,
  storage: Storage,
  underlyingNode: Node,
) : DataLocation(path, storage, underlyingNode)
