package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.String

public abstract class RemoteDataLocation(
  authenticity: Authenticity,
  transportEncryption: TransportEncryption,
  path: String,
  storage: Storage,
) : DataLocation(path, storage)
