package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

/**
 * Represents an entry point that can be triggered remotely, such as a network endpoint.
 */
public abstract class RemoteEntryPoint(
  underlyingNode: Node,
) : EntryPoint(underlyingNode)
