package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class RemoteEntryPoint(
  underlyingNode: Node,
) : EntryPoint(underlyingNode)
