package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Resource(
  public val creation_time: ZonedDateTime,
  public val description: String,
  public val labels: MutableMap<String, String>,
  name: String,
  public val raw: String,
  public val parent: Resource,
  underlyingNode: Node,
) : Concept(underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
