package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import java.time.ZonedDateTime
import kotlin.String
import kotlin.collections.MutableMap

public abstract class Resource(
  creation_time: ZonedDateTime,
  description: String,
  id: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Concept(underlyingNode)
