package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.Duration
import kotlin.Boolean
import kotlin.String

public abstract class ResourceLogging(
  enabled: Boolean,
  monitoringEnabled: Boolean,
  name: String,
  retentionPeriod: Duration,
  securityAlertsEnabled: Boolean,
  loggingService: LoggingService,
  underlyingNode: Node,
) : Logging(enabled, monitoringEnabled, name, retentionPeriod, securityAlertsEnabled,
    loggingService, underlyingNode)
