package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String

public abstract class SchemaValidation(
  format: String,
  schemaURL: String,
  errors: Error,
  underlyingNode: Node,
) : Functionality(underlyingNode)
