package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.String
import kotlin.collections.MutableList

public abstract class SchemaValidation(
  public val format: String,
  public val schemaURL: String,
  public val errors: MutableList<Error>,
  underlyingNode: Node,
) : Functionality(underlyingNode)
