package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import java.time.ZonedDateTime
import kotlin.Array
import kotlin.Boolean
import kotlin.Short
import kotlin.String
import kotlin.collections.MutableMap

public abstract class SecurityAdvisoryService(
  keies: Key,
  securityAdvisoryFeeds: SecurityAdvisoryFeed,
  ports: Array<Short>,
  ips: Array<String>,
  authenticity: Boolean,
  serviceMetadataDocument: ServiceMetadataDocument,
  computes: Compute,
  transportEncryption: TransportEncryption,
  internetAccessibleEndpoint: Boolean,
  redundancies: Redundancy,
  loggings: Logging,
  geoLocation: GeoLocation,
  usageStatistics: UsageStatistics,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
) : NetworkService(ports, ips, authenticity, serviceMetadataDocument, computes, transportEncryption,
    internetAccessibleEndpoint, redundancies, loggings, geoLocation, usageStatistics, raw,
    creation_time, labels, name, description, id, parent)
