package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.MutableList
import kotlin.collections.MutableMap

public abstract class SecurityAdvisoryDocument(
  public val vulnerabilities: MutableList<Vulnerability?>,
  filetype: String?,
  documentChecksums: MutableList<DocumentChecksum?>,
  documentSignatures: MutableList<DocumentSignature?>,
  securityFeatures: MutableList<SecurityFeature?>,
  validatedBy: SchemaValidation?,
  dataLocation: DataLocation?,
  creation_time: ZonedDateTime?,
  description: String?,
  labels: MutableMap<String, String>?,
  name: String?,
  raw: String?,
  parent: Resource?,
  underlyingNode: Node?,
) : Document(filetype, documentChecksums, documentSignatures, securityFeatures, validatedBy,
    dataLocation, creation_time, description, labels, name, raw, parent, underlyingNode) {
  init {
    name?.let { this.name = Name(localName = it) }
  }

  override fun equals(other: Any?): Boolean = other is SecurityAdvisoryDocument &&
              super.equals(other) &&
              other.vulnerabilities == this.vulnerabilities

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              vulnerabilities,
          )
}
