package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class SecurityTraining(
  annualUpdateCompleted: Boolean,
  successfullyCompletedPercentage: Boolean,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
  underlyingNode: Node,
) : Training(annualUpdateCompleted, successfullyCompletedPercentage, raw, creation_time, labels,
    name, description, id, parent, underlyingNode)
