package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.collections.MutableList

public abstract class SecurityAdvisoryFeed(
  public val securityAdvisoryDocuments: MutableList<SecurityAdvisoryDocument>,
  underlyingNode: Node,
) : Functionality(underlyingNode)
