package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class SecurityTraining(
  annualUpdateCompleted: Boolean,
  successfullyCompletedPercentage: Boolean,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Training(annualUpdateCompleted, successfullyCompletedPercentage, creation_time, description,
    labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
