package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.Boolean

public abstract class SingleSignOn(
  enabled: Boolean,
  contextIsChecked: Boolean,
) : Authenticity(contextIsChecked)
