package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import kotlin.Boolean

public abstract class TokenBasedAuthentication(
  enforced: Boolean,
  enabled: Boolean,
  contextIsChecked: Boolean,
) : Authenticity(contextIsChecked)
