package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.Float
import kotlin.String

public abstract class TransportEncryption(
  enforced: Boolean,
  enabled: Boolean,
  protocolVersion: Float,
  protocol: String,
  cipherSuites: CipherSuite,
  underlyingNode: Node,
) : Confidentiality(underlyingNode)
