package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean
import kotlin.Float
import kotlin.String

public abstract class TransportEncryption(
  public val enabled: Boolean,
  public val enforced: Boolean,
  public val protocol: String,
  public val protocolVersion: Float,
  public val cipherSuites: CipherSuite,
  basedOn: Cipher,
  secret: Secret,
  underlyingNode: Node,
) : Encryption(basedOn, secret, underlyingNode)
