package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept

public abstract class UnlockEncryptedDisk(
  linkedConcept: DiskEncryption,
  concept: Concept,
  underlyingNode: Node,
) : DiskEncryptionOperation(linkedConcept, concept, underlyingNode)
