package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node

public abstract class UnlockEncryptedDisk(
  linkedConcept: DiskEncryption,
  codeRegion: CodeRegion,
  underlyingNode: Node,
) : DiskEncryptionOperation(linkedConcept, codeRegion, underlyingNode)
