package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class UnlockEncryptedDisk(
  linkedConcept: DiskEncryption,
  underlyingNode: Node?,
) : DiskEncryptionOperation(linkedConcept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is UnlockEncryptedDisk &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
