package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

public abstract class UsageStatistics(
  public val apiHitsPerMonth: Int,
  underlyingNode: Node,
) : Auditing(underlyingNode) {
  override fun equals(other: Any?): Boolean = other is UsageStatistics &&
              super.equals(other) &&
              other.apiHitsPerMonth == this.apiHitsPerMonth

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
              apiHitsPerMonth,
          )
}
