package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Int

public abstract class UsageStatistics(
  public val apiHitsPerMonth: Int,
  underlyingNode: Node,
) : Auditing(underlyingNode)
