package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.util.Objects
import kotlin.Any
import kotlin.Boolean
import kotlin.Int

/**
 * Represents an operation to check the validity of a JWT token.
 */
public abstract class ValidateJwt(
  linkedConcept: Authenticity,
  underlyingNode: Node?,
) : AuthenticationOperation(linkedConcept, underlyingNode) {
  override fun equals(other: Any?): Boolean = other is ValidateJwt &&
              super.equals(other)

  override fun hashCode(): Int = Objects.hash(
              super.hashCode(),
          )
}
