package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Name
import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class VirtualMachine(
  public val activityLogging: ActivityLogging,
  public val automaticUpdates: AutomaticUpdates,
  public val blockStorage: BlockStorage,
  public val bootLogging: BootLogging,
  public val malwareProtection: MalwareProtection,
  public val osLogging: OSLogging,
  encryptionInUse: EncryptionInUse,
  networkInterfaces: NetworkInterface,
  remoteAttestation: RemoteAttestation,
  resourceLogging: ResourceLogging,
  internetAccessibleEndpoint: Boolean,
  geoLocation: GeoLocation,
  loggings: Logging,
  redundancies: Redundancy,
  usageStatistics: UsageStatistics,
  creation_time: ZonedDateTime,
  description: String,
  labels: MutableMap<String, String>,
  name: String,
  raw: String,
  parent: Resource,
  underlyingNode: Node,
) : Compute(encryptionInUse, networkInterfaces, remoteAttestation, resourceLogging,
    internetAccessibleEndpoint, geoLocation, loggings, redundancies, usageStatistics, creation_time,
    description, labels, name, raw, parent, underlyingNode) {
  init {
    this.name = Name(localName = name)
  }
}
