package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import java.time.ZonedDateTime
import kotlin.Boolean
import kotlin.String
import kotlin.collections.MutableMap

public abstract class VirtualMachine(
  blockStorage: BlockStorage,
  activityLogging: ActivityLogging,
  automaticUpdates: AutomaticUpdates,
  bootLogging: BootLogging,
  malwareProtection: MalwareProtection,
  osLogging: OSLogging,
  networkInterfaces: NetworkInterface,
  encryptionInUse: EncryptionInUse,
  remoteAttestation: RemoteAttestation,
  resourceLogging: ResourceLogging,
  internetAccessibleEndpoint: Boolean,
  redundancies: Redundancy,
  loggings: Logging,
  geoLocation: GeoLocation,
  usageStatistics: UsageStatistics,
  raw: String,
  creation_time: ZonedDateTime,
  labels: MutableMap<String, String>,
  name: String,
  description: String,
  id: String,
  parent: Resource,
  underlyingNode: Node,
) : Compute(networkInterfaces, encryptionInUse, remoteAttestation, resourceLogging,
    internetAccessibleEndpoint, redundancies, loggings, geoLocation, usageStatistics, raw,
    creation_time, labels, name, description, id, parent, underlyingNode)
