package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

/**
 * A WAF is a L7 firewall that includes L3 capabilities
 */
public abstract class WebApplicationFirewall(
  public val enabled: Boolean,
  underlyingNode: Node,
) : Firewall(underlyingNode)
