package de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated

import de.fraunhofer.aisec.cpg.graph.Node
import kotlin.Boolean

public abstract class WebApplicationFirewall(
  public val enabled: Boolean,
  underlyingNode: Node,
) : Firewall(underlyingNode)
