/*
 * Copyright (c) 2025, Fraunhofer AISEC. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *                    $$$$$$\  $$$$$$$\   $$$$$$\
 *                   $$  __$$\ $$  __$$\ $$  __$$\
 *                   $$ /  \__|$$ |  $$ |$$ /  \__|
 *                   $$ |      $$$$$$$  |$$ |$$$$\
 *                   $$ |      $$  ____/ $$ |\_$$ |
 *                   $$ |  $$\ $$ |      $$ |  $$ |
 *                   \$$$$$   |$$ |      \$$$$$   |
 *                    \______/ \__|       \______/
 *
 */
package de.fraunhofer.aisec.cpg

import com.squareup.kotlinpoet.ARRAY
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.DOUBLE
import com.squareup.kotlinpoet.FLOAT
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MUTABLE_MAP
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.SHORT
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import de.fraunhofer.aisec.cpg.models.ClassAbstractRepresentation
import de.fraunhofer.aisec.cpg.models.Properties
import java.io.File
import java.io.FileWriter
import java.io.IOException
import kotlin.collections.plus

fun writeKotlinClassesToFolder(
    sources: MutableList<ClassAbstractRepresentation>,
    outputBase: String,
    owl3: OWLCloudOntologyReader,
) {
    // This method adds the Concept class to the ontology, which is necessary for the root nodes to extend from it.
    // The Concept class is not defined in the ontology, so we have to add it manually.
    // For Code generation this class will be ignored. Can be seen as a helper
    addConceptClassToOntology(sources)

    var filepath: String
    for (ktSource in sources) {

        // This is necessary to avoid writing the Concept class (which is already defined in another package)
        if (ktSource.name.equals("Concept")) continue

        filepath = outputBase + "/" + ktSource.name + ".kt"
        val f = File(filepath)
        val directory = f.parentFile
        if (!directory.exists()) {
            if (!directory.mkdirs()) {
                println("Could not create base directory for file $outputBase")
            }
        }
        try {
            val fileWriter = FileWriter(f)
            fileWriter.write(createKtSourceCodeString(ktSource, owl3, sources))
            fileWriter.close()
            println("File written to: $filepath")
        } catch (e: IOException) {
            e.printStackTrace()
        }
    }
}

// This function is needed to add let the root nodes inherit from concept class since this is not
// reflected in the ontology
private fun addConceptClassToOntology(sources: MutableList<ClassAbstractRepresentation>) {
    // Create a new ClassAbstractRepresentation for the Concept class
    val conceptClass = ClassAbstractRepresentation(name = "Concept", parentClass = "")

    // Add the underlyingNode property to the Concept class
    conceptClass.objectProperties += Properties("Node", "underlyingNode")
    conceptClass.packageName = "de.fraunhofer.aisec.cpg.graph"

    // Iterate over all sources and add the Concept class to every class which does not have a
    // parent class
    for (ktSource in sources) {
        if (ktSource.parentClass == "" || ktSource.parentClass == "owl:Thing") {
            // If the class has no parent, add the Concept class as a parent
            ktSource.allParents += conceptClass
        }
    }
    // Add the Concept class to the sources list
    sources.add(0, conceptClass) // Add it at the beginning to ensure it is processed first
}

private fun createKtSourceCodeString(
    ktSource: ClassAbstractRepresentation,
    owl3: OWLCloudOntologyReader,
    otherClassAbstractions: List<ClassAbstractRepresentation>,
): String {
    if (ktSource.name == "owl:Thing") {
        return ""
    }

    // build parent class in order to extend from it
    // Get the parent interface/class using its fully-qualified name.
    var classBuilder = TypeSpec.classBuilder(ktSource.name).addModifiers(KModifier.ABSTRACT)

    if (ktSource.parentClass != "" && ktSource.parentClass != "owl:Thing") {
        val parentClass =
            ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", ktSource.parentClass)
        classBuilder =
            TypeSpec.classBuilder(ktSource.name)
                .superclass(parentClass)
                .addModifiers(KModifier.ABSTRACT)
    }

    // Create a constructor builder for adding parameters.
    val constructorBuilder = FunSpec.constructorBuilder()

    // writes own class properties into the constructor
    addPropertiesToClass(
        ktSource.dataProperties,
        ktSource.objectProperties,
        constructorBuilder,
        classBuilder,
        ktSource.name,
    )

    // Retrieve parents recursively and add them to the class.
    findAllParentsAndSaveToClassAbstraction(ktSource, otherClassAbstractions)

    // Now we have to add each object and data property of all parents to the constructor of
    // ktSource
    for (parent in ktSource.allParents) {
        // Write properties of parents into the constructor
        addPropertiesToClass(
            parent.dataProperties,
            parent.objectProperties,
            constructorBuilder,
            classBuilder,
            ktSource.name,
            isParent = true,
        )
    }

    // Set the primary constructor for the class.
    classBuilder.primaryConstructor(constructorBuilder.build())

    // Build the final file
    val file =
        FileSpec.builder(ktSource.packageName!!, ktSource.name)
            .addType(classBuilder.build())
            .build()
    return file.toString()
}

private fun addPropertiesToClass(
    dataProperties: List<Properties>,
    objectProperties: List<Properties>,
    constructorBuilder: FunSpec.Builder,
    classBuilder: TypeSpec.Builder,
    className: String,
    isParent: Boolean = false,
) {
    // Loop over the data properties.
    for (dataProp in dataProperties) {
        // Determine the correct TypeName based on the property type string.
        val typeName: TypeName = extractDataProperties(dataProp)

        if (typeName == ClassName("unknown", "unknown")) {
            println(
                "Unknown type: ${dataProp.propertyType} for property ${dataProp.propertyName} of class ${className}"
            )
        }

        // Add a constructor parameter for the property.
        constructorBuilder.addParameter(dataProp.propertyName, typeName)

        // Add a property to the class, initialized from the constructor parameter.
        classBuilder.primaryConstructor(constructorBuilder.build())

        if (isParent) {
            // Add SuperclassConstructorParameter for the property.
            classBuilder.addSuperclassConstructorParameter(dataProp.propertyName).build()
        }
    }

    // Loop over the object properties.
    for (objectProp in objectProperties) {
        val typeName = extractObjectProperties(objectProp)

        if (typeName == ClassName("unknown", "unknown")) {
            println("Unknown type: ${objectProp.propertyType}")
        }

        // Add a constructor parameter for the property.
        constructorBuilder.addParameter(objectProp.propertyName, typeName)

        // Add a property to the class, initialized from the constructor parameter.
        classBuilder.primaryConstructor(constructorBuilder.build())

        if (isParent) {
            // Add SuperclassConstructorParameter for the property.
            classBuilder.addSuperclassConstructorParameter(objectProp.propertyName).build()
        }
    }
}

private fun findAllParentsAndSaveToClassAbstraction(
    abstraction: ClassAbstractRepresentation,
    classAbstractions: List<ClassAbstractRepresentation>,
): ClassAbstractRepresentation? {
    // Find direct parent
    val directParent = classAbstractions.find { it.name == abstraction.parentClass }

    if (directParent != null) {
        // Add direct parent to allParents
        abstraction.allParents += directParent

        // Find and add parent's parents recursively
        findAllParentsAndSaveToClassAbstraction(directParent, classAbstractions)

        // Add all parents of parent to this abstraction's allParents
        abstraction.allParents += directParent.allParents

        //        if (abstraction.name != "owl:Thing") {
        //            println(
        //                "Found all parents of ${abstraction.name}:
        // ${abstraction.allParents.joinToString { it.name }}"
        //            )
        //        }

        return directParent
    }
    return null
}

private fun extractDataProperties(dataProp: Properties): TypeName {
    val typeName: TypeName =
        when (dataProp.propertyType) {
            "java.time.Duration" -> ClassName("java.time", "Duration")
            "java.time.ZonedDateTime" -> ClassName("java.time", "ZonedDateTime")
            "Short" -> SHORT
            "String" -> STRING
            "int" -> INT
            "Double" -> DOUBLE
            "Float",
            "float" -> FLOAT
            "boolean" -> BOOLEAN
            "de.fraunhofer.aisec.cpg.graph.declarations.FunctionDeclaration" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.declarations", "FunctionDeclaration")
            "de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.statements.expressions", "Expression")
            "de.fraunhofer.aisec.cpg.graph.Node" ->
                ClassName("de.fraunhofer.aisec.cpg.graph", "Node")
            "de.fraunhofer.aisec.cpg.graph.statements.expressions.CallExpression" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.statements.expressions", "CallExpression")
            "java.util.List<de.fraunhofer.aisec.cpg.graph.declarations.TranslationUnitDeclaration>" ->
                ClassName("java.util", "List")
                    .parameterizedBy(
                        ClassName(
                            "de.fraunhofer.aisec.cpg.graph.declarations",
                            "TranslationUnitDeclaration",
                        )
                    )
            "java.util.List<de.fraunhofer.aisec.cpg.graph.statements.expressions.CallExpression>" ->
                ClassName("java.util", "List")
                    .parameterizedBy(
                        ClassName(
                            "de.fraunhofer.aisec.cpg.graph.statements.expressions",
                            "CallExpression",
                        )
                    )
            "java.util.Map<String, String>" -> MUTABLE_MAP.parameterizedBy(STRING, STRING)
            "java.util.ArrayList<String>" -> ARRAY.parameterizedBy(STRING)
            "java.util.ArrayList<Short>" -> ARRAY.parameterizedBy(SHORT)

            "dateTime" -> ClassName("java.time", "ZonedDateTime") // TODO: Check if this is correct
            "listString" ->
                ClassName("java.util", "List")
                    .parameterizedBy(STRING) // TODO: Check if this is correct
            else -> ClassName("unknown", "unknown")
        }
    return typeName
}

private fun extractObjectProperties(objectProp: Properties): TypeName {
    val typeName =
        when (objectProp.propertyType) {
            "ApplicationLogging" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "ApplicationLogging",
                )
            "Functionality" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Functionality")
            "Compute" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Compute")
            "GeoLocation" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "GeoLocation")
            "[]Resource" ->
                ARRAY.parameterizedBy(
                    ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Resource")
                )
            "NetworkInterface" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "NetworkInterface",
                )
            "Image" -> ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Image")
            "ResourceLogging" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "ResourceLogging")
            "Container" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Container")
            "DatabaseStorage" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "DatabaseStorage")
            "DatabaseService" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "DatabaseService")
            "Storage" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Storage")
            "Authenticity" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Authenticity")
            "TransportEncryption" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "TransportEncryption",
                )
            "HttpEndpoint" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "HttpEndpoint")
            "Application" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Application")
            "HttpRequestHandler" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "HttpRequestHandler",
                )
            "Authorization" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Authorization")
            "AccessRestriction" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "AccessRestriction",
                )
            "NetworkService" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "NetworkService")
            "Logging" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Logging")
            "LoggingService" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "LoggingService")
            "IsAuthenticity" -> BOOLEAN
            "ObjectStorage" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "ObjectStorage")
            "IsTransportEncryption" -> BOOLEAN
            "IsAtRestEncryption" -> BOOLEAN
            "Immutability" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Immutability")
            "BlockStorage" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "BlockStorage")
            "AutomaticUpdates" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "AutomaticUpdates",
                )
            "BootLogging" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "BootLogging")
            "MalwareProtection" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "MalwareProtection",
                )
            "OSLogging" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "OSLogging")
            "Redundancy" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Redundancy")
            "UsageStatistics" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "UsageStatistics")
            "EncryptionInUse" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "EncryptionInUse")
            "RemoteAttestation" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "RemoteAttestation",
                )
            "ActivityLogging" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "ActivityLogging")
            "Resource" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Resource")
            "ServiceMetadataDocument" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "ServiceMetadataDocument",
                )
            "Backup" -> ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Backup")
            "CodeModule" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "CodeModule")
            "CodeRepository" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "CodeRepository")
            "DataLocation" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "DataLocation")
            "SchemaValidation" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "SchemaValidation",
                )
            "DocumentChecksum" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "DocumentChecksum",
                )
            "SecurityFeature" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "SecurityFeature")
            "DocumentSignature" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "DocumentSignature",
                )
            "SecurityAdvisoryFeed" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "SecurityAdvisoryFeed",
                )
            "CipherSuite" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "CipherSuite")
            "Error" -> ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Error")
            "AnomalyDetection" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "AnomalyDetection",
                )
            "CodeRegion" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "CodeRegion")
            "IsAccessRestriction" -> BOOLEAN
            "MachineLearning" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "MachineLearning")
            "Key" -> ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Key")
            "Vulnerability" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Vulnerability")
            "Infrastructure" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Infrastructure")
            "AtRestEncryption" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "AtRestEncryption",
                )
            "Library" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Library")
            "Credential" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Credential")
            "Function" ->
                ClassName("de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated", "Function")
            "SecurityAdvisoryDocument" ->
                ClassName(
                    "de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated",
                    "SecurityAdvisoryDocument",
                )
            "Node" -> ClassName("de.fraunhofer.aisec.cpg.graph", "Node")
            "Concept" -> ClassName("de.fraunhofer.aisec.cpg.graph", "Concept")

            else -> ClassName("unknown", "unknown")
        }
    return typeName
}
