coverage:
  range: "70...95"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 75%
comment:
    layout: "condensed_header, files, condensed_footer"
