title: "Meeting minutes for XX.XX.2023"
labels: ["minutes"]
body:
  - type: markdown
    attributes:
      value: |
        This discussion contains the public minutes of the dev meeting conducted on the date in the title. 
        It can be created ahead of time (ideally at least a week before) to fill the initial agenda and 
        list of PRs to discuss.
  - type: textarea
    id: agenda
    attributes:
      label: Agenda
      description: "What is/was the general of the meeting?"
      value: |
        1. Open PRs
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: prs
    attributes:
      label: Discussed PRs
      description: "Which PRs should be discussed / where discussed in the meeting?"
      value: |
        - [ ] #
        - [ ] #
        - [ ] #
        ...
    validations:
      required: true
  