/*
 * Copyright (c) 2025, Fraunhofer AISEC. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *                    $$$$$$\  $$$$$$$\   $$$$$$\
 *                   $$  __$$\ $$  __$$\ $$  __$$\
 *                   $$ /  \__|$$ |  $$ |$$ /  \__|
 *                   $$ |      $$$$$$$  |$$ |$$$$\
 *                   $$ |      $$  ____/ $$ |\_$$ |
 *                   $$ |  $$\ $$ |      $$ |  $$ |
 *                   \$$$$$   |$$ |      \$$$$$   |
 *                    \______/ \__|       \______/
 *
 */
package de.fraunhofer.aisec.cpg.graph.concepts.manualExtensions

import de.fraunhofer.aisec.cpg.graph.Node
import de.fraunhofer.aisec.cpg.graph.concepts.Concept
import de.fraunhofer.aisec.cpg.graph.concepts.Operation
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.Authenticity
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.Authorization
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.AutomaticUpdates
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.DatabaseQuery
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.DatabaseService
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.DatabaseStorage
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.HttpClient
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.HttpEndpoint
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.HttpRequest
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.HttpRequestContext
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.LogLevel
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.LogWrite
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.Logging
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.LoggingService
import de.fraunhofer.aisec.cpg.graph.concepts.autoGenerated.TransportEncryption
import de.fraunhofer.aisec.cpg.graph.concepts.http.HttpMethod
import java.time.Duration

/** The [underlyingNode] gets the current time of the system. */
class GetCurrentTime(concept: Concept, underlyingNode: Node?) :
    Operation(concept = concept, underlyingNode = underlyingNode)

class LoggingWithLevel(
    val logLevelThreshold: LogLevel?,
    enabled: Boolean?,
    monitoringEnabled: Boolean?,
    name: String?,
    retentionPeriod: Duration?,
    securityAlertsEnabled: Boolean?,
    loggingService: LoggingService?,
    underlyingNode: Node?,
) :
    Logging(
        enabled,
        monitoringEnabled,
        name,
        retentionPeriod,
        securityAlertsEnabled,
        loggingService,
        underlyingNode,
    )

class InputValidation(
    val input: Node?,
    val validatedOutput: Node?,
    concept: Concept,
    underlyingNode: Node?,
) : Operation(concept, underlyingNode)

class LogWriteWithArguments(
    val logArguments: List<Node?>,
    logLevel: LogLevel?,
    override val concept: LoggingWithLevel,
    underlyingNode: Node?,
) : LogWrite(logLevel, concept, underlyingNode)

class HttpClientWithProtocol(
    var protocol: TransportEncryption?,
    authenticity: Authenticity?,
    underlyingNode: Node?,
) :
    HttpClient(
        isTLS = protocol is TLS,
        authenticity = authenticity,
        underlyingNode = underlyingNode,
    )

class HttpRequestWithArguments(
    val arguments: List<Node>,
    val httpMethod: HttpMethod?,
    val url: String?,
    call: String?,
    reqBody: String?,
    httpEndpoint: HttpEndpoint?,
    linkedConcept: HttpClientWithProtocol,
    underlyingNode: Node?,
) :
    HttpRequest(
        call = call,
        reqBody = reqBody,
        httpEndpoint = httpEndpoint,
        linkedConcept = linkedConcept,
        underlyingNode = underlyingNode,
    )

class DatabaseQueryWithInput(
    val parameters: List<Node>,
    modify: Boolean?,
    calls: java.util.List<String>?,
    databaseService: DatabaseService?,
    storage: DatabaseStorage?,
    linkedConcept: DatabaseStorage,
    underlyingNode: Node?,
) :
    DatabaseQuery(
        modify = modify,
        calls = calls,
        databaseService = databaseService,
        storage = storage,
        linkedConcept = linkedConcept,
        underlyingNode = underlyingNode,
    )

class RateLimiting(val maxRequests: Int, val timeWindowSeconds: Int, underlyingNode: Node?) :
    Concept(underlyingNode)

class ExtendedHttpEndpoint(
    val rateLimiting: RateLimiting?,
    val maxInputSize: Int?,
    val userInput: MutableList<Node>,
    handler: String?,
    method: String?,
    path: String?,
    url: String?,
    authenticity: Authenticity?,
    authorization: Authorization?,
    httpRequestContext: HttpRequestContext?,
    proxyTarget: HttpEndpoint?,
    transportEncryption: TransportEncryption?,
    underlyingNode: Node?,
) :
    HttpEndpoint(
        handler,
        method,
        path,
        url,
        authenticity,
        authorization,
        httpRequestContext,
        proxyTarget,
        transportEncryption,
        underlyingNode,
    )

class InstallUpdate(val update: AutomaticUpdates, underlyingNode: Node?) :
    Operation(concept = update, underlyingNode = underlyingNode)
