//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>

// ------------------------ Structures ------------------------

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t _Z14initTLSContextv(void);
int32_t _Z22failSetInsecureCiphersP10ssl_ctx_st(int32_t * a1);
int32_t _Z23failDisableVerificationP10ssl_ctx_st(int32_t * a1);
int32_t _Z25failSetInsecureCiphersSTLP10ssl_ctx_st(int32_t * a1);
int32_t _Z28failSetInsecureCiphersGlobalP10ssl_ctx_st(int32_t * a1);
int32_t _Z29failSetInsecureCiphersLiteralP10ssl_ctx_st(int32_t * a1);
int32_t _Z9connectToNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi(int32_t a1, int32_t a2);
int32_t function_10d04(int32_t a1, int32_t a2, int32_t * a3, int32_t a4);
int32_t function_10d1c(int32_t a1);
int32_t function_10d40(int32_t a1, int32_t a2, int32_t a3);
int32_t function_10d58(void);
int32_t function_10d7c(int32_t a1);
int32_t function_10d88(int32_t a1);
int32_t function_10ddc(int32_t a1);
int32_t function_10de8(int32_t a1);
int32_t function_10e00(int32_t a1);
int32_t function_10e0c(int32_t a1, int32_t * a2, int32_t a3, int32_t * a4);
int32_t function_10e48(int32_t a1);
int32_t function_10e60(int32_t a1);
int32_t function_10e78(int32_t a1, int32_t a2, int32_t * a3);
int32_t function_10e84(int32_t a1, int32_t a2);

// --------------------- Global Variables ---------------------

int32_t g1 = -0x1ad24ffc; // 0x11664
int32_t g2 = 0; // 0x21eec
int32_t g3 = 0; // 0x220c0
int32_t g4 = 0; // 0x22180
int32_t g5 = 0; // 0x22210
int32_t g6;

// ------------------------ Functions -------------------------

// Address range: 0x10d04 - 0x10d10
int32_t function_10d04(int32_t a1, int32_t a2, int32_t * a3, int32_t a4) {
    // 0x10d04
    return SSL_set_fd();
}

// Address range: 0x10d1c - 0x10d28
int32_t function_10d1c(int32_t a1) {
    // 0x10d1c
    return SSL_new();
}

// Address range: 0x10d40 - 0x10d4c
int32_t function_10d40(int32_t a1, int32_t a2, int32_t a3) {
    // 0x10d40
    return OPENSSL_init_ssl();
}

// Address range: 0x10d58 - 0x10d64
int32_t function_10d58(void) {
    // 0x10d58
    return ERR_get_error();
}

// Address range: 0x10d7c - 0x10d88
int32_t function_10d7c(int32_t a1) {
    // 0x10d7c
    return SSL_CIPHER_get_name();
}

// Address range: 0x10d88 - 0x10d94
int32_t function_10d88(int32_t a1) {
    // 0x10d88
    return TLSv1_2_client_method();
}

// Address range: 0x10ddc - 0x10de8
int32_t function_10ddc(int32_t a1) {
    // 0x10ddc
    return SSL_CTX_new();
}

// Address range: 0x10de8 - 0x10df4
int32_t function_10de8(int32_t a1) {
    // 0x10de8
    return __cxa_end_cleanup();
}

// Address range: 0x10e00 - 0x10e0c
int32_t function_10e00(int32_t a1) {
    // 0x10e00
    return SSL_connect();
}

// Address range: 0x10e0c - 0x10e18
int32_t function_10e0c(int32_t a1, int32_t * a2, int32_t a3, int32_t * a4) {
    // 0x10e0c
    return SSL_CTX_set_cipher_list();
}

// Address range: 0x10e48 - 0x10e54
int32_t function_10e48(int32_t a1) {
    // 0x10e48
    return SSL_get_current_cipher();
}

// Address range: 0x10e60 - 0x10e6c
int32_t function_10e60(int32_t a1) {
    // 0x10e60
    return SSL_get_verify_result();
}

// Address range: 0x10e78 - 0x10e84
int32_t function_10e78(int32_t a1, int32_t a2, int32_t * a3) {
    // 0x10e78
    return SSL_CTX_set_verify();
}

// Address range: 0x10e84 - 0x10e90
int32_t function_10e84(int32_t a1, int32_t a2) {
    // 0x10e84
    return ERR_error_string();
}

// Address range: 0x10fa4 - 0x11104
// Demangled:     connectTo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
int32_t _Z9connectToNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi(int32_t a1, int32_t a2) {
    int32_t sock_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10fd4
    if (sock_fd == 0) {
        // 0x10fe8
        puts("Error creating socket.");
        // 0x110f8
        return -1;
    }
    int32_t v1 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g4, "Connecting to "); // 0x11000
    int32_t v2 = _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE((int32_t *)v1, (int32_t *)a1); // 0x11010
    _ZNSolsEPFRSoS_E((int32_t * (*)(int32_t *))_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int32_t *)v2, "..."));
    int32_t addr; // bp-28, 0x10fa4
    memset(&addr, 0, 16);
    addr = 2;
    inet_addr((char *)_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv());
    htons(443);
    int32_t v3 = connect(sock_fd, (struct sockaddr *)&addr, 16); // 0x11094
    int32_t result = sock_fd; // 0x110b0
    if (v3 != 0) {
        int32_t v4 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g4, "Error connecting to server."); // 0x110bc
        _ZNSolsEPFRSoS_E((int32_t * (*)(int32_t *))v4);
        result = -1;
    }
    // 0x110f8
    return result;
}

// Address range: 0x11124 - 0x11150
// Demangled:     failDisableVerification(ssl_ctx_st*)
int32_t _Z23failDisableVerificationP10ssl_ctx_st(int32_t * a1) {
    // 0x11124
    return function_10e78((int32_t)a1, 1, &g1);
}

// Address range: 0x11154 - 0x111c0
// Demangled:     failSetInsecureCiphers(ssl_ctx_st*)
int32_t _Z22failSetInsecureCiphersP10ssl_ctx_st(int32_t * a1) {
    int32_t v1 = 0x3a4c4c41; // bp-24, 0x11180
    return function_10e0c((int32_t)a1, &v1, 0, &v1);
}

// Address range: 0x111c8 - 0x111f0
// Demangled:     failSetInsecureCiphersLiteral(ssl_ctx_st*)
int32_t _Z29failSetInsecureCiphersLiteralP10ssl_ctx_st(int32_t * a1) {
    // 0x111c8
    int32_t v1; // 0x111c8
    return function_10e0c((int32_t)a1, (int32_t *)"ALL:!ADH", v1, (int32_t *)v1);
}

// Address range: 0x111f4 - 0x112b4
// Demangled:     failSetInsecureCiphersSTL(ssl_ctx_st*)
int32_t _Z25failSetInsecureCiphersSTLP10ssl_ctx_st(int32_t * a1) {
    // 0x111f4
    _ZNSaIcEC1Ev();
    int32_t v1; // bp-36, 0x111f4
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_((char *)&v1, (int32_t *)"ALL:!ADH");
    _ZNSaIcED1Ev();
    int32_t * v2 = (int32_t *)_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv(); // 0x11258
    int32_t v3; // bp-40, 0x111f4
    function_10e0c((int32_t)a1, v2, (int32_t)&v3, v2);
    int32_t result = _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev(); // 0x11280
    if (((int32_t)&g2 ^ (int32_t)&g2) != 0) {
        // 0x112a8
        __stack_chk_fail();
        result = &g6;
    }
    // 0x112ac
    return result;
}

// Address range: 0x112bc - 0x112e4
// Demangled:     failSetInsecureCiphersGlobal(ssl_ctx_st*)
int32_t _Z28failSetInsecureCiphersGlobalP10ssl_ctx_st(int32_t * a1) {
    // 0x112bc
    int32_t v1; // 0x112bc
    return function_10e0c((int32_t)a1, (int32_t *)"MD5", v1, (int32_t *)v1);
}

// Address range: 0x11308 - 0x11394
// Demangled:     initTLSContext()
int32_t _Z14initTLSContextv(void) {
    // 0x11308
    function_10d40(0, 0, 0);
    int32_t v1 = function_10d40(0x200002, 0, 0); // 0x11330
    int32_t result = function_10ddc(function_10d88(v1)); // 0x11340
    int32_t * v2 = (int32_t *)result; // 0x11350
    _Z22failSetInsecureCiphersP10ssl_ctx_st(v2);
    _Z29failSetInsecureCiphersLiteralP10ssl_ctx_st(v2);
    _Z25failSetInsecureCiphersSTLP10ssl_ctx_st(v2);
    _Z28failSetInsecureCiphersGlobalP10ssl_ctx_st(v2);
    function_10e78(result, 1, NULL);
    _Z23failDisableVerificationP10ssl_ctx_st(v2);
    return result;
}

// Address range: 0x11398 - 0x1163c
int main(int argc, char ** argv) {
    // 0x11398
    _ZNSaIcEC1Ev();
    int32_t v1; // bp-44, 0x11398
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_((char *)&v1, (int32_t *)"172.217.18.99");
    int32_t v2 = _Z9connectToNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi((int32_t)&v1, 2); // 0x113e8
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev();
    _ZNSaIcED1Ev();
    if (v2 < 0) {
        // 0x11630
        return -1;
    }
    int32_t v3 = function_10d1c(_Z14initTLSContextv()); // 0x11430
    g5 = v3;
    if (v3 == 0) {
        int32_t v4 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g4, "Error creating SSL."); // 0x11458
        _ZNSolsEPFRSoS_E((int32_t * (*)(int32_t *))v4);
        // 0x11630
        return -1;
    }
    // 0x11474
    function_10d04(v3, v2, &g5, v3);
    if (function_10e00(g5) <= 0) {
        int32_t v5 = function_10d58(); // 0x114ac
        int32_t v6 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g4, "Error creating SSL connection. Error Code: "); // 0x114c0
        int32_t v7 = function_10e84(v5, 0); // 0x114d4
        _ZNSolsEPFRSoS_E((int32_t * (*)(int32_t *))_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int32_t *)v6, (char *)v7));
        // 0x11630
        return -1;
    }
    // 0x11558
    if (function_10e60(g5) == 0) {
        int32_t v8 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g3, "Call to SSL_get_verify_result is ok"); // 0x1158c
        _ZNSolsEPFRSoS_E((int32_t * (*)(int32_t *))v8);
    }
    int32_t v9 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g3, "SSL communication established using "); // 0x115a8
    int32_t v10 = function_10d7c(function_10e48(g5)); // 0x115c8
    _ZNSolsEPFRSoS_E((int32_t * (*)(int32_t *))_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int32_t *)v9, (char *)v10));
    // 0x11630
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// int32_t __cxa_end_cleanup(void);
// void __stack_chk_fail(void);
// int32_t _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv(void);
// int32_t _ZNSaIcEC1Ev(void);
// int32_t _ZNSaIcED1Ev(void);
// int32_t _ZNSolsEPFRSoS_E(int32_t * (*a1)(int32_t *));
// int32_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_(char * a1, int32_t * a2);
// int32_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev(void);
// int32_t _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE(int32_t * a1, int32_t * a2);
// int32_t _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(int32_t * a1, char * a2);
// int connect(int fd, __CONST_SOCKADDR_ARG addr, socklen_t len);
// int32_t ERR_error_string(void);
// int32_t ERR_get_error(void);
// uint16_t htons(uint16_t hostshort);
// in_addr_t inet_addr(const char * cp);
// void * memset(void * s, int c, size_t n);
// int32_t OPENSSL_init_ssl(void);
// int puts(const char * s);
// int socket(int domain, int type, int protocol);
// int32_t SSL_CIPHER_get_name(void);
// int32_t SSL_connect(void);
// int32_t SSL_CTX_new(void);
// int32_t SSL_CTX_set_cipher_list(void);
// int32_t SSL_CTX_set_verify(void);
// int32_t SSL_get_current_cipher(void);
// int32_t SSL_get_verify_result(void);
// int32_t SSL_new(void);
// int32_t SSL_set_fd(void);
// int32_t TLSv1_2_client_method(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.3.0)
// Detected functions: 22

