name: build

on:
  - push
  - pull_request

jobs:
  # we need to at least execute one job otherwise the overall thing will fail, this is a known issue of GitHub actions
  # see https://github.community/t5/GitHub-Actions/Workflow-is-failing-if-no-job-can-be-ran-due-to-condition/td-p/38085
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: |
          echo 1
  build:
    runs-on: ubuntu-latest
    # only execute if this is coming from a push or from a PR from a forked repository
    # otherwise this will get executed twice for PR from internal branches
    if: github.event_name == 'push' || github.event_name == 'pull_request' && (github.event.pull_request.base.repo.full_name != github.event.pull_request.head.repo.full_name)
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build
        run: |
          if [ "$SONAR_TOKEN" != "" ]
          then
            ./gradlew --parallel spotlessCheck build sonarqube \
            -Dsonar.projectKey=Fraunhofer-AISEC_cpg_neo4j \
            -Dsonar.organization=fraunhofer-aisec \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
          else
            ./gradlew --parallel spotlessCheck build
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
