//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>

// ------------------------ Structures ------------------------

struct _Unwind_Exception {
    int32_t e0;
};

struct sockaddr {
    int64_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3);
int64_t _fini(void);
int64_t _GLOBAL__sub_I_ssl(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t _Z10callMeBackiP17x509_store_ctx_st(int32_t a1, int64_t * a2);
int64_t _Z14initTLSContextv(void);
int64_t _Z22failSetInsecureCiphersP10ssl_ctx_st(int64_t * a1);
int64_t _Z23failDisableVerificationP10ssl_ctx_st(int64_t * a1);
int64_t _Z25failSetInsecureCiphersSTLP10ssl_ctx_st(int64_t * a1);
int64_t _Z28failSetInsecureCiphersGlobalP10ssl_ctx_st(int64_t * a1);
int64_t _Z29failDisableVerificationLambdaP10ssl_ctx_st(int64_t * a1);
int64_t _Z29failSetInsecureCiphersLiteralP10ssl_ctx_st(int64_t * a1);
int64_t _Z41__static_initialization_and_destruction_0ii(int32_t a1, int32_t a2);
int64_t _Z9connectToNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi(int64_t a1, int32_t a2);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
void function_2220(int64_t * d);
int16_t function_2230(int16_t hostshort);
int64_t function_2240(int64_t a1, int64_t a2, int32_t a3);
int32_t function_2250(int32_t domain, int32_t type, int32_t protocol);
int64_t function_2260(int64_t a1);
int64_t function_2270(void);
int64_t function_2280(int64_t a1, int64_t a2);
int64_t * function_2290(int64_t * s, int32_t c, int32_t n);
int64_t function_22a0(void);
int64_t function_22b0(void);
int64_t function_22c0(int64_t a1);
int64_t function_22d0(void);
int32_t function_22e0(int32_t fd, struct sockaddr * addr, int32_t len);
int32_t function_22f0(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle);
int64_t function_2300(int64_t * a1, int64_t * a2);
int64_t function_2310(int64_t * a1, char * a2);
int32_t function_2320(char * cp);
int64_t function_2330(int64_t * (*a1)(int64_t *));
int64_t function_2340(void);
void function_2350(void);
int64_t function_2360(int64_t a1);
int64_t function_2370(int64_t a1);
int64_t function_2380(int64_t a1, int64_t * a2, int64_t * a3);
int64_t function_2390(char * a1, int64_t * a2);
int64_t function_23a0(void);
int32_t function_23b0(char * s);
int64_t function_23c0(int64_t a1);
int64_t function_23d0(int64_t a1);
void function_23e0(struct _Unwind_Exception * object);
int64_t function_23f0(void);
int64_t function_2400(int64_t a1, int64_t a2, int64_t a3);
int64_t function_2410(int64_t a1, int64_t a2);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x2500; // 0x4c70
int64_t g2 = 0x24c0; // 0x4c80
int64_t g3 = 0; // 0x4fc8
int64_t g4; // 0x5008
int64_t g5 = 0; // 0x5040
int64_t g6 = 0; // 0x5160
char g7 = 0; // 0x5270
int64_t g8 = 0; // 0x5278
int64_t g9 = 0; // 0x5280
int32_t g10;

// ------------------------ Functions -------------------------

// Address range: 0x2000 - 0x201b
int64_t _init(void) {
    int64_t result = 0; // 0x2012
    if (*(int64_t *)0x4fe8 != 0) {
        // 0x2014
        __gmon_start__();
        result = &g10;
    }
    // 0x2016
    return result;
}

// Address range: 0x2220 - 0x222b
void function_2220(int64_t * d) {
    // 0x2220
    __cxa_finalize(d);
}

// Address range: 0x2230 - 0x223b
int16_t function_2230(int16_t hostshort) {
    // 0x2230
    return htons(hostshort);
}

// Address range: 0x2240 - 0x224b
int64_t function_2240(int64_t a1, int64_t a2, int32_t a3) {
    // 0x2240
    return SSL_set_fd();
}

// Address range: 0x2250 - 0x225b
int32_t function_2250(int32_t domain, int32_t type, int32_t protocol) {
    // 0x2250
    return socket(domain, type, protocol);
}

// Address range: 0x2260 - 0x226b
int64_t function_2260(int64_t a1) {
    // 0x2260
    return SSL_new();
}

// Address range: 0x2270 - 0x227b
int64_t function_2270(void) {
    // 0x2270
    return _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv();
}

// Address range: 0x2280 - 0x228b
int64_t function_2280(int64_t a1, int64_t a2) {
    // 0x2280
    return OPENSSL_init_ssl();
}

// Address range: 0x2290 - 0x229b
int64_t * function_2290(int64_t * s, int32_t c, int32_t n) {
    // 0x2290
    return memset(s, c, n);
}

// Address range: 0x22a0 - 0x22ab
int64_t function_22a0(void) {
    // 0x22a0
    return ERR_get_error();
}

// Address range: 0x22b0 - 0x22bb
int64_t function_22b0(void) {
    // 0x22b0
    return _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev();
}

// Address range: 0x22c0 - 0x22cb
int64_t function_22c0(int64_t a1) {
    // 0x22c0
    return SSL_CIPHER_get_name();
}

// Address range: 0x22d0 - 0x22db
int64_t function_22d0(void) {
    // 0x22d0
    return TLSv1_2_client_method();
}

// Address range: 0x22e0 - 0x22eb
int32_t function_22e0(int32_t fd, struct sockaddr * addr, int32_t len) {
    // 0x22e0
    return connect(fd, addr, len);
}

// Address range: 0x22f0 - 0x22fb
int32_t function_22f0(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle) {
    // 0x22f0
    return __cxa_atexit(func, arg, dso_handle);
}

// Address range: 0x2300 - 0x230b
int64_t function_2300(int64_t * a1, int64_t * a2) {
    // 0x2300
    return _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE(a1, a2);
}

// Address range: 0x2310 - 0x231b
int64_t function_2310(int64_t * a1, char * a2) {
    // 0x2310
    return _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(a1, a2);
}

// Address range: 0x2320 - 0x232b
int32_t function_2320(char * cp) {
    // 0x2320
    return inet_addr(cp);
}

// Address range: 0x2330 - 0x233b
int64_t function_2330(int64_t * (*a1)(int64_t *)) {
    // 0x2330
    return _ZNSolsEPFRSoS_E(a1);
}

// Address range: 0x2340 - 0x234b
int64_t function_2340(void) {
    // 0x2340
    return _ZNSaIcED1Ev();
}

// Address range: 0x2350 - 0x235b
void function_2350(void) {
    // 0x2350
    __stack_chk_fail();
}

// Address range: 0x2360 - 0x236b
int64_t function_2360(int64_t a1) {
    // 0x2360
    return SSL_CTX_new();
}

// Address range: 0x2370 - 0x237b
int64_t function_2370(int64_t a1) {
    // 0x2370
    return SSL_connect();
}

// Address range: 0x2380 - 0x238b
int64_t function_2380(int64_t a1, int64_t * a2, int64_t * a3) {
    // 0x2380
    return SSL_CTX_set_cipher_list();
}

// Address range: 0x2390 - 0x239b
int64_t function_2390(char * a1, int64_t * a2) {
    // 0x2390
    return _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_(a1, a2);
}

// Address range: 0x23a0 - 0x23ab
int64_t function_23a0(void) {
    // 0x23a0
    return _ZNSt8ios_base4InitC1Ev();
}

// Address range: 0x23b0 - 0x23bb
int32_t function_23b0(char * s) {
    // 0x23b0
    return puts(s);
}

// Address range: 0x23c0 - 0x23cb
int64_t function_23c0(int64_t a1) {
    // 0x23c0
    return SSL_get_current_cipher();
}

// Address range: 0x23d0 - 0x23db
int64_t function_23d0(int64_t a1) {
    // 0x23d0
    return SSL_get_verify_result();
}

// Address range: 0x23e0 - 0x23eb
void function_23e0(struct _Unwind_Exception * object) {
    // 0x23e0
    _Unwind_Resume(object);
}

// Address range: 0x23f0 - 0x23fb
int64_t function_23f0(void) {
    // 0x23f0
    return _ZNSaIcEC1Ev();
}

// Address range: 0x2400 - 0x240b
int64_t function_2400(int64_t a1, int64_t a2, int64_t a3) {
    // 0x2400
    return SSL_CTX_set_verify();
}

// Address range: 0x2410 - 0x241b
int64_t function_2410(int64_t a1, int64_t a2) {
    // 0x2410
    return ERR_error_string();
}

// Address range: 0x2420 - 0x244f
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x2420
    int64_t v1; // 0x2420
    __libc_start_main(0x289d, (int32_t)a4, (char **)&v1, (void (*)())0x2bc0, (void (*)())0x2c30, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x2450 - 0x2479
int64_t deregister_tm_clones(void) {
    // 0x2450
    return 0x5020;
}

// Address range: 0x2480 - 0x24b9
int64_t register_tm_clones(void) {
    // 0x2480
    return 0;
}

// Address range: 0x24c0 - 0x24f9
int64_t __do_global_dtors_aux(void) {
    // 0x24c0
    if (g7 != 0) {
        // 0x24f8
        int64_t result; // 0x24c0
        return result;
    }
    // 0x24cd
    if (g3 != 0) {
        // 0x24db
        __cxa_finalize((int64_t *)*(int64_t *)0x5008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x24e7
    g7 = 1;
    return result2;
}

// Address range: 0x2500 - 0x2509
int64_t frame_dummy(void) {
    // 0x2500
    return register_tm_clones();
}

// Address range: 0x2509 - 0x2656
// Demangled:     connectTo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
int64_t _Z9connectToNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi(int64_t a1, int32_t a2) {
    int64_t v1 = __readfsqword(40); // 0x251c
    uint32_t sock_fd = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x253a
    int64_t v2; // 0x2509
    if (sock_fd != 0) {
        int64_t v3 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g6, "Connecting to "); // 0x256c
        int64_t v4 = _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE((int64_t *)v3, (int64_t *)a1); // 0x257e
        _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)v4, "..."));
        int64_t addr; // bp-40, 0x2509
        memset(&addr, 0, 16);
        addr = 2;
        inet_addr((char *)_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv());
        htons(443);
        if (connect(sock_fd, (struct sockaddr *)&addr, 16) == 0) {
            // 0x263d
            v2 = sock_fd;
        } else {
            int64_t v5 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g6, "Error connecting to server."); // 0x261c
            _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))v5);
            v2 = 0xffffffff;
        }
    } else {
        // 0x2548
        puts("Error creating socket.");
        v2 = 0xffffffff;
    }
    int64_t result = v2; // 0x264d
    if (v1 != __readfsqword(40)) {
        // 0x264f
        __stack_chk_fail();
        result = &g10;
    }
    // 0x2654
    return result;
}

// Address range: 0x2656 - 0x2681
// Demangled:     failDisableVerification(ssl_ctx_st*)
int64_t _Z23failDisableVerificationP10ssl_ctx_st(int64_t * a1) {
    // 0x2656
    return function_2400((int64_t)a1, 1, 0x2b3a);
}

// Address range: 0x2681 - 0x26dc
// Demangled:     failSetInsecureCiphers(ssl_ctx_st*)
int64_t _Z22failSetInsecureCiphersP10ssl_ctx_st(int64_t * a1) {
    int64_t v1 = __readfsqword(40); // 0x2691
    int64_t v2 = 0x484441213a4c4c41; // bp-25, 0x26aa
    function_2380((int64_t)a1, &v2, &v2);
    int64_t result = 0; // 0x26d3
    if (v1 != __readfsqword(40)) {
        // 0x26d5
        __stack_chk_fail();
        result = &g10;
    }
    // 0x26da
    return result;
}

// Address range: 0x26dc - 0x2702
// Demangled:     failSetInsecureCiphersLiteral(ssl_ctx_st*)
int64_t _Z29failSetInsecureCiphersLiteralP10ssl_ctx_st(int64_t * a1) {
    // 0x26dc
    int64_t v1; // 0x26dc
    return function_2380((int64_t)a1, (int64_t *)"ALL:!ADH", (int64_t *)v1);
}

// Address range: 0x2702 - 0x27d5
// Demangled:     failSetInsecureCiphersSTL(ssl_ctx_st*)
int64_t _Z25failSetInsecureCiphersSTLP10ssl_ctx_st(int64_t * a1) {
    int64_t v1 = __readfsqword(40); // 0x2713
    _ZNSaIcEC1Ev();
    int64_t v2; // bp-72, 0x2702
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_((char *)&v2, (int64_t *)"ALL:!ADH");
    _ZNSaIcED1Ev();
    int64_t * v3 = (int64_t *)_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv(); // 0x276a
    function_2380((int64_t)a1, v3, v3);
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev();
    int64_t result = 0; // 0x2789
    if (v1 != __readfsqword(40)) {
        // 0x27c9
        __stack_chk_fail();
        result = &g10;
    }
    // 0x27ce
    return result;
}

// Address range: 0x27d5 - 0x27fb
// Demangled:     failSetInsecureCiphersGlobal(ssl_ctx_st*)
int64_t _Z28failSetInsecureCiphersGlobalP10ssl_ctx_st(int64_t * a1) {
    // 0x27d5
    int64_t v1; // 0x27d5
    return function_2380((int64_t)a1, (int64_t *)"MD5", (int64_t *)v1);
}

// Address range: 0x27fb - 0x280a
// Demangled:     failDisableVerificationLambda(ssl_ctx_st*)
int64_t _Z29failDisableVerificationLambdaP10ssl_ctx_st(int64_t * a1) {
    // 0x27fb
    int64_t result; // 0x27fb
    return result;
}

// Address range: 0x280a - 0x289d
// Demangled:     initTLSContext()
int64_t _Z14initTLSContextv(void) {
    // 0x280a
    function_2280(0, 0);
    function_2280(0x200002, 0);
    int64_t result = function_2360(function_22d0()); // 0x283c
    int64_t * v1 = (int64_t *)result; // 0x284c
    _Z22failSetInsecureCiphersP10ssl_ctx_st(v1);
    _Z29failSetInsecureCiphersLiteralP10ssl_ctx_st(v1);
    _Z25failSetInsecureCiphersSTLP10ssl_ctx_st(v1);
    _Z28failSetInsecureCiphersGlobalP10ssl_ctx_st(v1);
    function_2400(result, 1, 0);
    _Z23failDisableVerificationP10ssl_ctx_st(v1);
    return result;
}

// Address range: 0x289d - 0x2b3a
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x28b1
    _ZNSaIcEC1Ev();
    int64_t v2; // bp-72, 0x289d
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_((char *)&v2, (int64_t *)"172.217.18.99");
    int64_t v3 = _Z9connectToNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi((int64_t)&v2, 2); // 0x28ef
    int32_t v4 = v3; // 0x28f4
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev();
    _ZNSaIcED1Ev();
    int64_t v5 = 0xffffffff; // 0x2913
    if (v4 >= 0) {
        int64_t v6 = function_2260(_Z14initTLSContextv()); // 0x292f
        g8 = v6;
        if (v6 != 0) {
            // 0x2979
            function_2240(v6, v3 & 0xffffffff, v4);
            int32_t v7 = function_2370(g8); // 0x299c
            if (v7 >= 0 == (v7 != 0)) {
                // 0x2a57
                if (function_23d0(g8) == 0) {
                    int64_t v8 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g5, "Call to SSL_get_verify_result is ok"); // 0x2a7e
                    _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))v8);
                }
                int64_t v9 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g5, "SSL communication established using "); // 0x2aa6
                int64_t v10 = function_22c0(function_23c0(g8)); // 0x2ac0
                _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)v9, (char *)v10));
                v5 = 0;
            } else {
                int64_t v11 = function_22a0(); // 0x29a5
                int64_t v12 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g6, "Error creating SSL connection. Error Code: "); // 0x29bb
                int64_t v13 = function_2410(0x100000000 * v11 >> 32, 0); // 0x29d0
                _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)v12, (char *)v13));
                v5 = 0xffffffff;
            }
        } else {
            int64_t v14 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(&g6, "Error creating SSL."); // 0x2955
            _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))v14);
            v5 = 0xffffffff;
        }
    }
    int64_t result = v5; // 0x2af7
    if (v1 != __readfsqword(40)) {
        // 0x2b2e
        __stack_chk_fail();
        result = &g10;
    }
    // 0x2b33
    return result;
}

// Address range: 0x2b3a - 0x2b50
// Demangled:     callMeBack(int, x509_store_ctx_st*)
int64_t _Z10callMeBackiP17x509_store_ctx_st(int32_t a1, int64_t * a2) {
    // 0x2b3a
    return 1;
}

// Address range: 0x2b50 - 0x2b9d
// Demangled:     __static_initialization_and_destruction_0(int, int)
int64_t _Z41__static_initialization_and_destruction_0ii(int32_t a1, int32_t a2) {
    int64_t result; // 0x2b50
    if (a1 == 1 == a2 == 0xffff) {
        // 0x2b71
        _ZNSt8ios_base4InitC1Ev();
        int32_t v1 = __cxa_atexit((void (*)(int64_t *))*(int64_t *)0x4ff8, &g9, &g4); // 0x2b95
        result = v1;
    }
    // 0x2b9a
    return result;
}

// Address range: 0x2b9d - 0x2bb6
int64_t _GLOBAL__sub_I_ssl(void) {
    // 0x2b9d
    return _Z41__static_initialization_and_destruction_0ii(1, 0xffff);
}

// Address range: 0x2bc0 - 0x2c25
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x2bec
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x2c16
        return result;
    }
    int64_t v1 = 0; // 0x2bf5
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x2c00
        v1++;
    }
    // 0x2c16
    return result;
}

// Address range: 0x2c30 - 0x2c35
int64_t __libc_csu_fini(void) {
    // 0x2c30
    int64_t result; // 0x2c30
    return result;
}

// Address range: 0x2c38 - 0x2c45
int64_t _fini(void) {
    // 0x2c38
    int64_t result; // 0x2c38
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int __cxa_atexit(void(* func)(void *), void * arg, void * dso_handle);
// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// void __stack_chk_fail(void);
// void _Unwind_Resume(struct _Unwind_Exception * object);
// int64_t _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv(void);
// int64_t _ZNSaIcEC1Ev(void);
// int64_t _ZNSaIcED1Ev(void);
// int64_t _ZNSolsEPFRSoS_E(int64_t * (*a1)(int64_t *));
// int64_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_(char * a1, int64_t * a2);
// int64_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev(void);
// int64_t _ZNSt8ios_base4InitC1Ev(void);
// int64_t _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE(int64_t * a1, int64_t * a2);
// int64_t _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(int64_t * a1, char * a2);
// int connect(int fd, __CONST_SOCKADDR_ARG addr, socklen_t len);
// int64_t ERR_error_string(void);
// int64_t ERR_get_error(void);
// uint16_t htons(uint16_t hostshort);
// in_addr_t inet_addr(const char * cp);
// void * memset(void * s, int c, size_t n);
// int64_t OPENSSL_init_ssl(void);
// int puts(const char * s);
// int socket(int domain, int type, int protocol);
// int64_t SSL_CIPHER_get_name(void);
// int64_t SSL_connect(void);
// int64_t SSL_CTX_new(void);
// int64_t SSL_CTX_set_cipher_list(void);
// int64_t SSL_CTX_set_verify(void);
// int64_t SSL_get_current_cipher(void);
// int64_t SSL_get_verify_result(void);
// int64_t SSL_new(void);
// int64_t SSL_set_fd(void);
// int64_t TLSv1_2_client_method(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.3.0)
// Detected functions: 53

