name: build-and-test-codyze

on:
  workflow_dispatch:
    inputs:
      codyzeBranch:
        description: 'The codyze branch to test'
        required: true
        default: main

jobs:
  build-and-test-codyze:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'codyze-check')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Build for Codyze
        run: |
          ./gradlew --parallel -Pversion=0.0.0-SNAPSHOT -x signMavenPublication -x javadoc publishToMavenLocal
      - name: Checkout and test codyze
        run: |
          git clone https://github.com/Fraunhofer-AISEC/codyze.git
          cd codyze
          git checkout ${{ github.event.inputs.codyzeBranch }}
          sed -i 's|cpg:\([0-9\.]*\).*|cpg:0.0.0-SNAPSHOT")|' build.gradle.kts
          ./gradlew --parallel test
